### ISSUE TITLE
Group crashes by location of crash in Objective C code

### ISSUE THREAD

**Issue by shimfish** [microsoft/appcenter#1931] opened 2020-07-19 13:14 UTC
Currently, all Objective-C objc_MsgSend SIGSEV crashes are all grouped together, even though they occur in different places in the code.

Would it be possible to group crashes more intelligently, for example by the location of the last line in symbolicated code in the stack?

**Comment by MatkovIvan** [comment] 2020-12-25 13:59
Hi @shimfish,
Sorry for the delay, but this is a duplicate of #348, so let's track the status of it there

**Closed by MatkovIvan** 2020-12-25 13:59 UTC
Labels: feature request
