### ISSUE TITLE
"Log Flow" in Events doesn't show any results

### ISSUE THREAD

**Issue by himanpan** [microsoft/appcenter#1227] opened 2019-10-19 07:29 UTC
"Log Flow" in our case just keeps showing "Awaiting data from your app" message, without showing any log records.
It was showing records previously. What has gone wrong suddenly?
Is there any way to figure out if this is an issue from app side and not appcenter?
If this is appcenter issue, any plan to fix it?

**Comment by Oddj0b** [comment] 2019-10-21 14:04
Hi @himanpan, thanks for reporting the bug. I've tagged my colleague who is located in the US so give a buffer for a response. Because this could be specific to your app, you can also contact support on our portal.

**Comment by sewil** [comment] 2020-01-22 09:51
Same problem. If it's any help, here's the console output:
```
bugsnag.js:2650 GET https://appcenter.ms/api/v0.1/apps/****/****/data/resource_provisioning 404
(anonymous) @ bugsnag.js:2650
F @ bluebird.js:1060
D._resolveFromExecutor @ bluebird.js:3364
D @ bluebird.js:2949
tt.fetch @ bugsnag.js:2648
e._fetch @ http-client.ts:179
(anonymous) @ http-client.ts:163
f @ bluebird.js:5397
D._settlePromiseFromHandler @ bluebird.js:3393
D._settlePromise @ bluebird.js:3450
D._settlePromise0 @ bluebird.js:3495
D._settlePromises @ bluebird.js:3575
l @ bluebird.js:145
c @ bluebird.js:138
u._drainQueues @ bluebird.js:154
drainQueues @ bluebird.js:67
Promise.then (async)
a @ bluebird.js:4620
u._queueTick @ bluebird.js:163
u.settlePromises @ bluebird.js:128
D._fulfill @ bluebird.js:3521
D._resolveCallback @ bluebird.js:3312
(anonymous) @ bluebird.js:3365
t @ bootstrap:25
(anonymous) @ fd28f1f8ea796ed08bb8.js:1
```

**Comment by hackzai** [comment] 2020-02-14 02:09
I also having this experience with AppCenter Nuget 2.6.4. But my app with older version of AppCenter SDK (2.1.1) still working good and all reported events are displayed on Log Flow or the Analytic overview screen.

**Comment by hackzai** [comment] 2020-02-16 04:04
> I also having this experience with AppCenter Nuget 2.6.4. But my app with older version of AppCenter SDK (2.1.1) still working good and all reported events are displayed on Log Flow or the Analytic overview screen.

I manage to isolate the root cause with AppCenter.LogLevel = LogLevel.Verbose.

Due to my Android is communicate with my local server by clear text http. So, I need to specified **appcenter.ms**  in the network_security_config.xml domain config to not user clear text.

**Comment by NightOwlCoder** [comment] 2020-02-24 21:53
We are seeing the same thing when running with v3, no log entries on log flow, and `LogLevel.Verbose` does not display any issues (on iOS).
If I wait long enough, I do see entries on events, so looks like it is just a localized issue with the `LogFlow` window.

Ideas on how I could help to figure this out?

**Comment by aheiz** [comment] 2020-06-19 11:51
Same over here for SDK version 3.2.2, LogFlow window is just empty (ios & android)

**Comment by Lelelo1** [comment] 2020-12-08 17:06
There is a `4.0.0` version out now.  It does not seem to have work either. Do I need to downgrade to `2.1.1` and the wait some hours to get the events?

**Comment by wim07101993** [comment] 2021-02-24 09:50
Is there any progress on this bug?

**Comment by scout208** [comment] 2021-04-08 17:01
Updating to version 4.2.0 seems to have fixed this issue for me

**Comment by DergachevE** [comment] 2023-01-04 19:47
Currently we are not observing such issues with the Log Flow functionality - looks like SDK update helped with this.
Closing this issue as of now.
Please feel free to re-open if the issue still persists

**Closed by DergachevE** 2023-01-04 19:47 UTC
Labels: bug, analytics, reviewed-DRI
