### ISSUE TITLE
Manual upload of crash reports

### ISSUE THREAD

**Issue by hydrixos** [microsoft/appcenter#1180] opened 2019-10-11 11:48 UTC
From time to time, customers send us crash reports via Mail. It would be great if we could just upload them to App Center in order to symbolicate them.

**Comment by lumaxis** [comment] 2019-10-11 17:15
Sounds like this might be a duplicate of #31? Which is actually currently being worked on 🙂

**Closed by lumaxis** 2019-10-11 17:15 UTC
Labels: diagnostics, duplicate, feature request
