### ISSUE TITLE
Appcenter.ms build setup page goes to blank page

### ISSUE THREAD

**Issue by onethread** [microsoft/appcenter#1029] opened 2019-09-13 21:15 UTC
When I click on the settings cog for my build, I get an empty page.

I.e. Browsing to https://appcenter.ms/users/user/apps/app/build/branches then clicking on the settings cog for my branch.

Safari reports `Failed to load resource: the server responded with a status of 404 ()` and `[Error] Unrecognized Content-Security-Policy directive 'worker-src'. (x9)` errors while Chrome reports `/api/v0.1/apps/user/app/alerts_bugtracker:1 Failed to load resource: the server responded with a status of 404 ()`

<img width="1379" alt="Screen Shot 2019-09-13 at 17 12 37" src="https://user-images.githubusercontent.com/593233/64895161-b2122100-d649-11e9-8454-af4c91037f8c.png">

**Comment by DennisPan** [comment] 2019-09-13 21:44
@onethread Could you reach out to support via the chat bubble on App Center portal? Also, does this only happen when you open the branch configuration page?

**Comment by ranterle** [comment] 2019-09-13 21:44
Hi there, thanks for reporting this, it seems you're seeing two issues (they might be related):
1. The configuration page for your branch won't open
2. You're seeing a bunch of HTTP 404 error messages in your browser console and other warnings/errors

For 1. it would be helpful if you can share your exact app information, i.e. the URL you have open when this issue occurs - can you open a conversation through the blue chat button in App Center portal to share this information with us? Also it would be good to understand whether you see this for all of your apps or only for a certain subset?

For 2. I can reproduce this to some extent but it doesn't look related to 1. at this time. Will track this independently.

**Comment by onethread** [comment] 2019-09-13 22:01
@DennisPan @ranterle I've reached out via chat bubble, but just to answer some of your questions:

It only happens for the master branch (and I only have one app). For branches that I've never configured deployment, the "Configure build" editor loads just fine.

The exact failing url is: https://appcenter.ms/users/onethread/apps/Arfa/build/branches/master/setup

**Comment by onethread** [comment] 2019-09-13 22:05
It was working yesterday. The only notable change I can see from a working setup page is that my master config used to point at an Xcode 11 beta, which is no longer a valid option.

**Comment by ranterle** [comment] 2019-09-13 22:10
Thanks @onethread - I think this actually helps us narrow it down, do you see any particular errors in your browser console that are not HTTP request related? i.e. JavaScript errors? Feel free to share either here or in the conversation.

**Comment by eashman** [comment] 2019-09-13 22:12
This just happened to me as well.  Glad to know I'm not the only one.  Can't do much of anything unless this is fixed.

So who is pushing out production code on a Friday night?  Serves them right... :)

**Comment by ranterle** [comment] 2019-09-13 22:13
@eashman do you also see the exact same behavior? Build configuration page not working anymore for a branch that previously had Xcode 11 Beta selected? or a similar result for different configuration?

**Comment by eashman** [comment] 2019-09-13 22:14
Mine doesn't have to do with using Xcode 11 Beta.  I just cannot open the Build configuration of any iOS branches.  My Android ones are still working.

**Comment by onethread** [comment] 2019-09-13 22:17
@ranterle Sorry, no JS errors. Console is clean, correcting for the request errors.

**Comment by DennisPan** [comment] 2019-09-13 22:20
@eashman Could you also reach out to support for this?

**Comment by DennisPan** [comment] 2019-09-13 22:36
Thanks for reaching out to support! That really helped. We've identified the issue, and are working on the fix.

**Comment by DennisPan** [comment] 2019-09-13 22:56
The issue is fixed now. Refresh the page and now it should load. Apology for the trouble. Thanks again for reaching out!

**Closed by DennisPan** 2019-09-13 22:56 UTC
