### ISSUE TITLE
Ability to use with Swift Packages

### ISSUE THREAD

**Issue by gogoslab** [microsoft/appcenter#1168] opened 2019-10-10 09:54 UTC
Add a Package.swift manifest file so the project

https://developer.apple.com/documentation/xcode/creating_a_swift_package_with_xcode

**Comment by MatkovIvan** [comment] 2019-11-08 22:40
Thanks for getting in touch!
It's a duplicate of recently transferred issue from SDK repository. Let's track this feature request there.

Duplicate of #1295

**Closed by MatkovIvan** 2019-11-08 22:40 UTC
Labels: feature request, sdk
