### ISSUE TITLE
Warnings from AppCenter when building iOS project with NativeAOT

### ISSUE THREAD

**Issue by charlesroddie** [microsoft/appcenter#2570] opened 2023-08-10 15:30 UTC
Build a Xamarin.IOS app using NativeAOT gives these warnings:
```
ILLINK : warning MT2387: It's not safe to remove the dynamic registrar, because Microsoft.AppCenter references 'ObjCRuntime.BlockLiteral.SetupBlockUnsafe (System.Delegate, System.Delegate)'. [/Users/runner/work/1/s/Platforms/iOS/50iOS.csproj]
ILLINK : warning MT2387: It's not safe to remove the dynamic registrar, because Microsoft.AppCenter.Crashes references 'ObjCRuntime.BlockLiteral.SetupBlockUnsafe (System.Delegate, System.Delegate)'. [/Users/runner/work/1/s/Platforms/iOS/50iOS.csproj]
```

From discord

> @filipnavara For the SetupBlockUnsafe it likely needs to be converted to UnmanagedCallersOnly and the BlockLiteral constructor pattern...
(If it's generated code then it may be just a matter of rebuilding it.)
I just had to do this today in our codebase 😅

**Comment by DmitriyKirakosyan** [comment] 2023-08-15 11:44
Hi @charlesroddie , thank you for the report!

If I understand it correctly, the warning is coming from the .NET IL Linker, right? We are not referencing `SetupBlockUnsafe` directly in code, so I believe it can come from some generated code or dependencies.
We will file an item on our board and will look into it.

Is it a blocker for you? Does the project build and run well with these warnings? Does the AppCenter SDK work correctly?
In case you find more details, context or a possible root cause, please share with us.

**Comment by filipnavara** [comment] 2023-08-15 11:55
We should move this issue to xamarin/xamarin-macios repo. This is result of not running the `OptimizeGeneratedCode` linker step, and we are discussing how to fix it.

**Comment by rolfbjarne** [comment] 2023-08-15 12:50
This issue was moved to xamarin/xamarin-macios#18736

**Comment by DmitriyKirakosyan** [comment] 2023-08-15 16:28
Thanks folks, closing.

**Closed by DmitriyKirakosyan** 2023-08-15 16:28 UTC
Labels: feature request, sdk
