### ISSUE TITLE
Manually upload a crash log

### ISSUE THREAD

**Issue by dn-paul** [microsoft/appcenter#1317] opened 2019-11-05 01:03 UTC
**Describe the solution you'd like**
Sometimes a user or a tester pulls a crash log from their device and sends it to me. I would like to be able to upload it to AppCenter for symbolication, manually. HockeyApp had this feature.

**Describe alternatives you've considered**
I've considered staying on HockeyApp as long as possible, or finding another service to use that allows this use case.

**Additional context**
Feature parity with HockeyApp before the transition is forced would be nice.

**Comment by cainejette** [comment] 2019-11-05 01:09
Hi there! 👋 We recently enabled this -- see docs [here](https://docs.microsoft.com/en-us/appcenter/diagnostics/features#upload-reports-to-app-center)

**Comment by derpixeldan** [comment] 2019-11-05 08:52
Duplicate of https://github.com/microsoft/appcenter/issues/289

**Comment by LGriffioen** [comment] 2019-11-07 13:23
@cainejette thanks for creating an API, but we really need a UI on the website where you can upload crash logs, like HockeyApp has. We have folks who are working with customers and don't have time to bother with upload scripts, they just need a simple way to drop the log into the website and view the symbolicated version.

**Comment by derpixeldan** [comment] 2019-11-07 13:39
@LGriffioen understood, we're working on it.

**Comment by winnie** [comment] 2020-01-30 01:57
Hey we recently completed this feature! You can now manually [upload Apple crash logs via the UI](https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes-ui) as shown below:

![image](https://user-images.githubusercontent.com/8868628/73413449-b62d9b00-42d9-11ea-99de-737f21fccf61.png)

Thanks!

**Closed by winnie** 2020-01-30 01:57 UTC
Labels: diagnostics, feature request, hockeyapp

**Comment by tucomel** [comment] 2020-07-04 21:54
@winnie there is no upload crash here on my interface
