### ISSUE TITLE
iOS:Track Error  

### ISSUE THREAD

**Issue by skhye05** [microsoft/appcenter#1643] opened 2020-01-21 00:15 UTC
I would to know if it's possible to track errors using handled exceptions implementation with iOS 

I know this feature currently exist on android when you call Crashes.trackError(...) methods, that perfectly implement the latter.

I would like to know if this feature already exist for iOS? 
and how to use it? 
if not how can one go about implementing it?

Thanks

**Comment by sindresorhus** [comment] 2020-02-10 12:13
I believe this is a duplicate of https://github.com/microsoft/appcenter/issues/192.

**Comment by Kalzem** [comment] 2020-02-26 08:39
Not a duplicate as Android, apparently, has this feature, while iOS/macOS is still waiting.

**Comment by winnie** [comment] 2020-02-28 16:16
Hey @Kalzem - thanks so much for the feedback. I wish I had a better answer for you but I don't have an ETA at the moment. I will post here when I have updates. 

Thanks!

**Comment by adriavernetta** [comment] 2020-04-02 10:17
> Hey @Kalzem - thanks so much for the feedback. I wish I had a better answer for you but I don't have an ETA at the moment. I will post here when I have updates.
> 
> Thanks!

Hi Winnie. We at Nestlé IT are being requested by markets for feedback on this feature availability. Is there any approximate ETA for that? Even if it's a Quarter or month plan can be useful for giving proper feedback to them.

Thanks and Best!

**Comment by MatkovIvan** [comment] 2020-04-07 12:57
Duplicate of #192

**Closed by MatkovIvan** 2020-04-07 12:57 UTC
Labels: feature request, sdk

**Comment by Trackerrorofficial** [comment] 2023-09-25 00:09
Visiting Our Site [Trackerror](https://trackerror.com/)

Have a nice day!
