### ISSUE TITLE
Support authentication to private NPM registries

### ISSUE THREAD

**Issue by atrauzzi** [microsoft/appcenter#399] opened 2019-05-09 12:40 UTC
I'm not able to find anywhere to configure my App Center project to authenticate to one of my Azure Devops private NPM package repositories.

Is this currently supported?

**Comment by DennisPan** [comment] 2019-05-16 20:25
@atrauzzi You are right that there is currently no direct support of this, but you should be able to achieve a solution with environment variables plus custom scripts. This example may help: https://blog.theodo.com/2018/07/installing-private-npm-packages-appcenter-2/

**Comment by atrauzzi** [comment] 2019-05-16 23:08
Great, thanks for the link.  I'll use that in the interim as you guys figure out the best way to streamline this. 😊

**Comment by DennisPan** [comment] 2019-05-16 23:33
Let us know if you run into any issue! Thanks for reaching out. I'm going to close this as we won't be able to get to this for a while given other priorities and that a solution exists. 

cc @nrajpurkar

**Closed by DennisPan** 2019-05-16 23:33 UTC
Labels: bug, build

**Comment by atrauzzi** [comment] 2019-05-18 21:26
@DennisPan - Hmm, it'd be better to leave this open and track it in a backlog somewhere.  Otherwise it will be forgotten and will never get considered for implementation.

**Comment by DennisPan** [comment] 2019-05-19 21:02
@atrauzzi Feel free to re-open it. At the very least I'm going to remove the "bug" label, as this is more of a feature request, not a bug. Thing change, so I cannot tell for sure, but given where we are in terms of priority, I doubt that we will get to something like this in the foreseeable future. If we get more interest from others, certainly we can revisit.

**Comment by pepoman** [comment] 2019-06-18 14:38
Hi,
I have been also running into the private feed problem, the mentioned fix worked for me but now is failing looking for nested dependencies, so I get a 400 error when running the build, I was thinking in NPM -ci in order to not look for updated dependencies but, after checking with your support, there is no way I can add any flags to the "npm install" command, could you please advice?

**Comment by DennisPan** [comment] 2019-06-19 17:07
@pepoman Do you mind reaching out to support again and ask them to assign the ticket to me? I'd like to take a deeper look at your build logs to understand more.

**Comment by phil-andrews** [comment] 2020-05-04 15:46
You can also do this using an .npmrc file in your project root. It's pretty simple. This is [a tutorial explaining the exact process](https://medium.com/@PhilipAndrews/installing-private-npm-packages-in-microsoft-appcenter-ci-cd-13d61f02aab2)

**Comment by Biciato** [comment] 2022-01-03 13:12
@phil-andrews using a .npmrc file didn't work for me

**Comment by atrauzzi** [comment] 2022-01-04 16:43
You shouldn't commit credentials to source control.
