### ISSUE TITLE
Support for .aab in Appcenter

### ISSUE THREAD

**Issue by PranavSwaroopTalla111** [microsoft/appcenter#2157] opened 2021-03-30 04:48 UTC
We are trying to distribute the app to app center using app bundle(.aab). But currently we see appFile takes Relative path from the repo root to the APK and IPA file to publish.So do we already have support for .aab file to publish in app center because play store will only be accepting .aab files  beginning August 2021.

**Comment by MatkovIvan** [comment] 2021-03-31 21:19
Duplicate of #955

**Closed by MatkovIvan** 2021-03-31 21:19 UTC
Labels: distribute, feature request
