### ISSUE TITLE
All Builds cancelled

### ISSUE THREAD

**Issue by jkobow** [microsoft/appcenter#747] opened 2019-07-19 17:24 UTC
**What App Center service does this affect?**
Builds

**Describe the bug**
When we run a build it starts but is cancelled immediately 

**To Reproduce**
1. Go to builds -> branches 
2. Click on the gear on a branch
3. Build Now

**Expected behavior**
Run a build

**Comment by nrajpurkar** [comment] 2019-07-19 17:32
Looks like the same as #746, we're aware of this and looking into the issue.

**Comment by DennisPan** [comment] 2019-07-20 16:29
@jkobow Thanks for reaching out. This issues should be fixed now. Let us now if you see anything else.

**Closed by DennisPan** 2019-07-20 16:29 UTC
Labels: bug

**Comment by IljaCuvasov** [comment] 2024-11-26 10:56
@dennispan the issue is back, same with #746

**Comment by dennispan** [comment] 2024-11-26 21:56
@IljaCuvasov sorry I no longer work on App Center
