### ISSUE TITLE
Failed to publish to store. Production version would become higher than alpha or beta

### ISSUE THREAD

**Issue by rhouweling** [microsoft/appcenter#643] opened 2019-06-27 12:25 UTC
**What App Center service does this affect?**
Distribution of Android app

**Describe the bug**
When I distribute my app, an error appears:
Failed to publish to store. Error: Production version code (70) would become higher than Alpha track version (51) and Beta track version 52) so Alpha and Beta tracks would be deactivated.

This didn't happen before and I already published multiple times. The alpha and beta apps were removed a couple of months ago but this issue didn't appear before.

I've attached an image of the error and an image of the empty Alpha and Beta tracks in the Play Console.

**To Reproduce**
Not sure how this can be reproduced on another account, but I have had an alpha and beta app in the past which are removed from the store, but are visible in the history of the alpha and beta tracks. When I publish a newer app to production, the error above appears.

**Expected behavior**
Successful publication of the app.

**Screenshots**
![icreative_appcenter_error](https://user-images.githubusercontent.com/50869531/60265954-4ee4de00-98e7-11e9-9d05-b288bd23b963.png)
![play store alpha and beta tracks](https://user-images.githubusercontent.com/50869531/60265964-51473800-98e7-11e9-83b4-45714398abb5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version ?

**Additional context**

**Comment by amchew** [comment] 2019-08-29 17:46
Thanks @rhouweling for reporting the bug! @botatoes would you mind taking a look please?

**Comment by sm1th** [comment] 2019-09-25 18:22
I am also getting this error when I try to distribute to my Production channel (via my master branch) when I have a previous build in my Alpha Channel (from my develop branch).

**Comment by Oddj0b** [comment] 2019-10-07 08:05
This is a duplicate of feature request #740, give it a :+1: reaction.

**Closed by Oddj0b** 2019-10-07 08:05 UTC
Labels: bug, stores

**Comment by PrgrmmrOleg** [comment] 2021-02-14 20:08
I am using react native.
How I`m working with versionCode.
I added MODE = alpha/beta/prod variable to **.env** file

And then I added in build.gradle file  (_**youApp/android/app/build.gradle**_) versionCode generate method.


   ```
   ...
    def date = new Date()
    def minuteTimeStamp =  (date.getTime()).toString().take(8)
    def formattedDate = "00" + minuteTimeStamp
    if (project.env.get("MODE").equals("alpha")) {
        formattedDate = "01" + minuteTimeStamp
    }
    if (project.env.get("MODE").equals("beta")) {
        formattedDate = "02" + minuteTimeStamp
    }
    def code = formattedDate.toInteger()
    ...
    defaultConfig {
        ...
        versionCode code
        versionName "1.4.16"
        ....
     }
     ...
```


This is not the best option, but it allows you to automatically generate a version of the code while the version of the production code will be lower than alpha and beta, but higher than its previous one.

Note: You need to disable auto generation of the code version for android in the app center.

The code version is updated once a minute. Also a certain limitation, but I don't think that you will need to upload the application to the store more often)

**Comment by kristof-lambaerts-aca** [comment] 2023-11-10 14:04
Still an issue. Why would it be a problem for a production version to become higher than alpha or beta? It's literally meant to be like that because it comes after that in the release cycle.
