### ISSUE TITLE
.NET 6 Support

### ISSUE THREAD

**Issue by kondareddy** [microsoft/appcenter#2444] opened 2022-07-20 01:46 UTC
Looks like we don't have .net 6 supporting nuget package?

Any timeline for same?

**Comment by DmitriyKirakosyan** [comment] 2022-07-20 19:37
Hi @kondareddy , thank you for reaching out!
Are you talking about AppCenter SDK Nugets or Xamarin.UITest Nugets?

**Comment by kondareddy** [comment] 2022-07-21 23:19
Thanks for reply.

I am migrating our app from .NET 4.6 to .NET 6 and referring to AppCenter SDK.

to be precise
AppCenter.Analytics.Metrics.dll
Microsoft.AppCenter.Analytics.dll
Microsoft.AppCenter.Crashes.dll

**Comment by DmitriyKirakosyan** [comment] 2022-07-22 10:06
Thank  you for the clarification.
We are working on .NET 6 support, but no ETA at this moment.

As for `Microsoft.AppCenter.Analytics.Metrics.dll`, this is not an official AppCenter SDK dll and thus it is not under our control.

I'm closing it as a duplicate of https://github.com/microsoft/appcenter-sdk-dotnet/issues/1660 and https://github.com/microsoft/appcenter-sdk-dotnet/issues/1647.

**Closed by DmitriyKirakosyan** 2022-07-22 10:06 UTC
Labels: feature request

**Comment by MatkovIvan** [comment] 2022-07-22 10:10
@kondareddy .NET 6 cannot consume existing (in our package) TFMs only on iOS/macOS platform, in case of Windows (based on your .NET Framework 4.6 mention) it should pickup existing .NET 5 binaries
