### ISSUE TITLE
I am directed to the login page for public groups.

### ISSUE THREAD

**Issue by hozat06** [microsoft/appcenter#2633] opened 2024-05-07 14:21 UTC
Hello,

The groups I created publicly were working smoothly so far.

Knowing the links, the user could access the groups and the application anonymously. Currently, when we want to access the link from the browser on Android and iOS operating systems, it redirects to the login page.

Can you check it?

**Comment by keehun** [comment] 2024-05-07 14:59
I have noticed this as well this morning, and the timeline of @hozat06's report matches mine.

**Comment by thibault-ml** [comment] 2024-05-07 15:04
We have noticed this too: public pages used to work without requiring anybody to log in, but now it requires users to log in. 

This is despite the "App can be downloaded by anyone with link access" being turned ON. I tried turning it off and on again, to no avail.

**Comment by fabiendem** [comment] 2024-05-07 15:10
Same, I've sent a message to the AppCenter support as well just in case...
Nothing relevant on the Status page https://status.appcenter.ms/

**Comment by fabiendem** [comment] 2024-05-07 15:28
@hozat06 @thibault-ml @keehun AppCenter Support got back to me. It should be fixed now.
Working fine for me 👍

**Comment by ankasani** [comment] 2024-05-07 15:31
Hi All, Sorry for the inconvenience, Please can you check now and let us know if you are still facing the issue ?

**Comment by thibault-ml** [comment] 2024-05-07 15:34
This is working for us now! Thank you :-)

What was the problem, out of curiosity? It wasn't on the incident page either, so it was difficult to confirm whether we had misconfigured something :D

**Comment by hozat06** [comment] 2024-05-08 07:04
Thanks. The problem is fixed.

**Comment by ankasani** [comment] 2024-05-08 07:23
@thibault-ml Our backend team has identified that the issue was caused due to misconfiguration during the routine update that led to the issue.

**Comment by aw-cf** [comment] 2024-05-17 08:44
@ankasani looks the issue is back now!

**Comment by DmitriyKirakosyan** [comment] 2024-06-07 10:23
Closing the issue.

**Closed as completed by DmitriyKirakosyan** 2024-06-07 10:23 UTC
Labels: feature request, distribute
