### ISSUE TITLE
Publish to UWP Store

### ISSUE THREAD

**Issue by BrunoBlanes** [microsoft/appcenter#1126] opened 2019-10-02 18:46 UTC
**Describe the solution you'd like**
I would like to use AppCenter to publish UWP apps to the Windows Store.

**Comment by leoniDEV** [comment] 2019-10-02 19:49
This is a duplicate of this #383

**Comment by botatoes** [comment] 2019-10-02 20:48
Closing this one and keeping track of 383

**Closed by botatoes** 2019-10-02 20:48 UTC
Labels: feature request
