### ISSUE TITLE
App Center Crashes MAUI iOS App

### ISSUE THREAD

**Issue by plattski** [microsoft/appcenter#2482] opened 2022-11-02 16:54 UTC
I am unable to get App Center to work with my iOS app in MAUI. Just creating the basic MAUI app, adding the Nuget packages, adding the call to AppCenter.Start, crashes it every time.  Using iPad with iOS v15.6.1 Sample code online at https://drive.google.com/file/d/15pIPuWaYemGzMFZHIlBupamsrI0lOyNC/view?usp=share_link.  Deugger console output reads:

[0:] An error occurred: 'Could not create an native instance of the type 'Microsoft.AppCenter.Apple.Bindings.MSACWrapperSdk': the native class hasn't been loaded.
It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.'. Callstack: '   at Foundation.NSObject.InitializeObject(Boolean alloced)
   at Foundation.NSObject..ctor(NSObjectFlag x)
   at Microsoft.AppCenter.Apple.Bindings.MSACWrapperSdk..ctor(String wrapperSdkVersion, String wrapperSdkName, String wrapperRuntimeVersion, String liveUpdateReleaseLabel, String liveUpdateDeploymentKey, String liveUpdatePackageHash)
   at Microsoft.AppCenter.AppCenter.SetWrapperSdk()
   at Microsoft.AppCenter.AppCenter.PlatformStart(String appSecret, Type[] services)
   at Microsoft.AppCenter.AppCenter.Start(String appSecret, Type[] services)
   at AppCenterTest.App.OnStart() in D:\AppCenterTest\AppCenterTest\App.xaml.cs:line 21
   at Microsoft.Maui.Controls.Application.SendStart()
   at Microsoft.Maui.Controls.Window.Microsoft.Maui.IWindow.Created()
   at Microsoft.Maui.LifecycleEvents.AppHostBuilderExtensions.<>c.<OnConfigureLifeCycle>b__1_0(UIApplication app, NSDictionary launchOptions)
   at Microsoft.Maui.MauiUIApplicationDelegate.<>c__DisplayClass6_0.<FinishedLaunching>b__0(FinishedLaunching del)
   at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[FinishedLaunching](IServiceProvider services, Action`1 action)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at AppCenterTest.Program.Main(String[] args) in D:\AppCenterTest\AppCenterTest\Platforms\iOS\Program.cs:line 13
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)'
The app has been terminated.

**Comment by MikhailSuendukov** [comment] 2022-11-03 11:10
Hi @plattski and thanks for providing the demo project. I would also like to clarify on which platform you are building your project and which version of .NET you are using. Also, it seems to be a duplicate of [this issue](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1692). So I close this issue.

**Closed by MikhailSuendukov** 2022-11-03 11:10 UTC
Labels: feature request

**Comment by plattski** [comment] 2022-11-03 13:28
You’re right, it does seem to be a duplicate. So I’ll move it there.
