### ISSUE TITLE
Xamarin.UITest(3.2.3 - 4.3.2) AppDataMode.Clear and AppDataMode.Auto for a physical iOS device throws an exception (macOS Monterey)

### ISSUE THREAD

**Issue by Moshex** [microsoft/appcenter#2319] opened 2021-11-15 18:30 UTC
When updating to Xamarin.UITest(3.2.3 - 4.3.2) AppDataMode.Clear and AppDataMode.Auto for a physical iOS device throws an exception this is with macOS Monterey, Xcode Version 13.1, and the latest Visual Studios updated as of 11/15/2021. The startup code needs to look like this:

```
            .iOS
            .WaitTimes(new CustomWaitTimes())
            .DeviceIdentifier(deviceId)
            .InstalledApp({bundle id})
            .EnableLocalScreenshots()
            .DisableSpecFlowIntegration()
            .StartApp(AppDataMode.Auto);
            Or
            .StartApp(AppDataMode.Clear);
```

The exceptions are as follows:

```
Xamarin.UITest.XDB.Exceptions.DeviceAgentException : Failed to clear data for app {bundle id}


ExitCode: 134
/var/folders/g1/1jz4c5yd6bx41bgkjh7vmdw80000gn/T/Empty.xcappdata
Nov 15 11:23:05  iOSDeviceManager[7145] <Notice>: _AMDDeviceAttachedCallbackv3 (thread 0x11038b600): Device 'AMDevice 0x600000858000 {UDID = 00008030-000448463438802E, device ID = 1, location ID = 0x14324400, product ID = 0x12a8}' attached.
Nov 15 11:23:05  iOSDeviceManager[7145] <Notice>: _SubscribeForMuxNotifications (thread 0x11038b600): returned 0x0.
Nov 15 11:23:05  iOSDeviceManager[7145] <Notice>: _UsbMuxSecureStartService (thread 0x11038b600): returned 0 starting service com.apple.mobile.installation_proxy on device 00008030-000448463438802E at port 50688, out fd = -1.
Nov 15 11:23:05  iOSDeviceManager[7145] <Notice>: AMDeviceStopSession (thread 0x11038b600): returned 0x0 for device 1
Nov 15 11:23:05  iOSDeviceManager[7145] <Notice>: AMDeviceStopSession (thread 0x11038b600): returned 0x0 for device 1
Nov 15 11:23:05  iOSDeviceManager[7145] <Notice>: AMDeviceStopSession (thread 0x11038b600): returned 0x0 for device 1
Nov 15 11:23:05  iOSDeviceManager[7145] <Notice>: AMDeviceStopSession (thread 0x11038b600): returned 0x0 for device 1
Nov 15 11:23:05  iOSDeviceManager[7145] <Notice>: AMDeviceStopSession (thread 0x11038b600): returned 0x0 for device 1
Nov 15 11:23:05  iOSDeviceManager[7145] <Notice>: AMDeviceStopSession (thread 0x11038b600): returned 0x0 for device 1
Nov 15 11:23:05  iOSDeviceManager[7145] <Notice>: AMDeviceStopSession (thread 0x70000b31e000): returned 0x0 for device 1

```

**Comment by Lug16** [comment] 2021-12-19 04:32
Same thing here

**Comment by Moshex** [comment] 2021-12-20 20:46
@Lug16  I did the same but lost functionality for iOS, I really hope they fix this issue!

**Comment by smardine** [comment] 2022-02-07 15:38
+1 still exist in 3.2.6

**Comment by jstrawther** [comment] 2022-02-15 16:07
The documentation for the [iOSAppConfigurator.StartApp(AppDataMode) Method](https://docs.microsoft.com/en-us/dotnet/api/xamarin.uitest.configuration.iosappconfigurator.startapp?view=xamarin-uitest-sdk) states the following for the appDataMode parameter: 

> appDataMode
[AppDataMode](https://docs.microsoft.com/en-us/dotnet/api/xamarin.uitest.configuration.appdatamode?view=xamarin-uitest-sdk)
> The app data mode. Whether to clear app data or not before app launch. **Currently only supported in Xamarin Test Cloud.**

Should it be possible to clear data when running on a physical device outside of Xamarin Test Cloud?

**Comment by Moshex** [comment] 2022-02-16 19:01
@jstrawther 
This feature does not really apply to app-center since when app-center does its run it always does a fresh install every test for the app that you are testing. When it comes to local runs if you are coding and want to work off a physical device "AppDataMode.Clear" was the perfect feature to mirror how it runs on app-center. With this feature being broken and causing an exception it has lowered Xamarin.UITest automation framwork quality. The hope is that with any automation framework there should not be any method of that framework that causes a build error exception and this issue should be fixed as soon as possible.

**Comment by jstrawther** [comment] 2022-02-16 19:20
@Moshex Yes, i'm with you, and agree there is a bug here. What I was getting at, and should have stated in my comment, is that I wonder if we should expect a fix to support data clearing for local physical devices, or if (as it sounds from the API docs) the data clearing behavior is no longer supported outside of test cloud. If the latter, then i'd expect a fix to maybe involve changing the API or defaults, without adding support for the data clearing.

**Comment by smardine** [comment] 2022-04-17 22:39
Please don't close it 🤞

**Comment by Moshex** [comment] 2022-04-25 22:25
This bug is still open on version 3.2.7

**Comment by peitschie** [comment] 2022-04-27 00:09
As a workaround for this, I've leveraged `ios-deploy` directly from my test framework in a pre-test hook. E.g.,
```
ios-deploy --uninstall --bundle \"{Settings.IPAFile}\" --id \"{Settings.RealDeviceID}\" --bundle_id \"{Settings.iOSAppID}\"
```

Would be great if this was actually fixed in the library however, as it definitely used to work.

**Comment by smardine** [comment] 2022-04-27 12:24
> As a workaround for this, I've leveraged `ios-deploy` directly from my test framework in a pre-test hook. E.g.,
> 
> ```
> ios-deploy --uninstall --bundle \"{Settings.IPAFile}\" --id \"{Settings.RealDeviceID}\" --bundle_id \"{Settings.iOSAppID}\"
> ```
> 
> Would be great if this was actually fixed in the library however, as it definitely used to work.

Could you share some code? Is it in the initialization method ?

Thanks anyway for the tips 😁

**Comment by Moshex** [comment] 2022-04-27 20:10
A workaround that I have been using was to have the devs code me an app data clear button that is tied to the main page logo (kind of a hidden button) of the application that only works in the application's debug mode and not for prod. This button clears all the application data via the app and what is stored on the device that does make the application work like it's a fresh install. 

I don't think this is ideal but it was the best workaround I could think of to deal with this. 
I am not the biggest fan of using "ios-deploy" since that requires uninstalling the application and only using the IPA while I prefer using the bundle id to start the application. 

I really hope they fix this issue soon this really sucks for how long this has been broken

**Comment by IlyaBausovAkvelon** [comment] 2022-05-05 09:05
Hi all, we are currently working on fix for this. It will be fixed in the future release.

**Comment by smardine** [comment] 2022-05-05 09:48
Can't wait 🎉🎉

**Comment by axsha** [comment] 2022-05-10 06:43
Same problem here. Is there a forecast when the fix will be available?

**Comment by Moshex** [comment] 2022-05-11 15:30
Thank you so much @IlyaBausovAkvelon  for looking into this!

**Comment by Banley** [comment] 2022-06-02 16:21
Has anyone been able to test the latest version 3.2.8? I just tried with data mode set to auto and it seems 3.2.8 did not fix this for me. Reverted to 3.2.7 with .StartApp(Xamarin.UITest.Configuration.AppDataMode.DoNotClear) and it still works for me. I don't see any mention of this in the notes for 3.2.8 so I assume this fix is still on the way.

**Comment by Moshex** [comment] 2022-06-02 17:37
This issue still happens on version 3.2.8 I will update this ticket to reflect that.

**Comment by Banley** [comment] 2022-08-02 12:32
As far as I can tell, this is still an issue. There has been no update from dev on this error. Keep open please.

**Comment by sliovino** [comment] 2022-08-02 14:09
This issue still happens on version 3.2.8 with.StartApp(Xamarin.UITest.Configuration.AppDataMode.**Clear)**;
I need the fix as soon as possible because affect the execution of my test cases. I'm not able to clear the data from the app.

**Comment by Moshex** [comment] 2022-11-01 13:41
This issue is still open and needs a update to be fixed

**Comment by Viktor027** [comment] 2022-11-11 08:41
Hi all.
I've the same problem. Even when I don't use AppDataMode.Clear. I tried to decrease Xamarin UI library to 3.2.7 and It didn't help. Please solve this problem as faster as possible. We haven't any ways to run UI tetsts for physical iOS devices now.

**Comment by Banley** [comment] 2022-11-16 15:42
> Hi all. I've the same problem. Even when I don't use AppDataMode.Clear. I tried to decrease Xamarin UI library to 3.2.7 and It didn't help. Please solve this problem as faster as possible. We haven't any ways to run UI tetsts for physical iOS devices now.

@Viktor027: Try specifying "AppDataMode.DoNotClear". This should allow the tests to run. If you simply remove "AppDataMode.Clear", not specifying any data mode, it will default to Auto, which then defaults to Clear, which is currently broken, as noted here.

**Comment by Moshex** [comment] 2022-12-01 19:55
@Banley
@IlyaBausovAkvelon
@sliovino

After my testing on (12-01-2022):
This issue stated in the bug still happens in version 4.0.1 I will update this ticket to reflect that. Note, {AppDataMode.DoNotClear} does still work in version 4.0.1

**Comment by IlyaBausovAkvelon** [comment] 2022-12-01 23:23
We will try to fix it in the next release.

**Comment by Banley** [comment] 2022-12-22 17:46
Do we dare try this on MacOS 13? I call 'not it.'

**Comment by Moshex** [comment] 2023-01-26 15:02
This bug is still open on version 4.1.0

**Comment by IlyaBausovAkvelon** [comment] 2023-01-30 18:18
@Moshex we are going to fix it.

**Comment by Banley** [comment] 2023-03-22 14:13
Can we see an update for this issue? I am currently having trouble running tests on ios simulators due to not being able to clear the app. [Some tests pass, others fail due to the app having not been cleared and reset as expected before the next test starts.]

**Comment by OliverMDr** [comment] 2023-03-28 10:02
As UI-Tests are an essential part of our Deployment Pipeline this bug is a really big impediment for us at the moment. Please fix it as soon as possible. Or do you know when we can expect a fix? So that we know if we have to look for workarounds...

**Comment by IlyaBausovAkvelon** [comment] 2023-03-29 07:49
The issue is known and we are planning to fix it in the future.

**Comment by Moshex** [comment] 2023-10-24 13:45
This issue can't be tested on version 4.3.0 due to not allowing Xamarin.Uitest to run on a physical device at all. See here for reference:
https://github.com/microsoft/appcenter/issues/2475#issuecomment-1774214848

**Comment by dude3133** [comment] 2023-10-24 18:19
> > But that is also reproducing on local build 🤔
> 
> Are you talking about on an iOS Simulator? AppDataMode.Clear does work for me on an iOS Simulator just not a Physical device.

I mean iOS device

Unfortunately, there are no Xamarin.UITest repo to report that issue separately

**Comment by Moshex** [comment] 2023-10-24 18:30
> Xamarin.UITest repo

as far as I know, this is where you report issues with Xamarin.UITest repo and yes this issue is just with a Physical iOS device. This does work on App Center and Simulators.

**Comment by Moshex** [comment] 2023-11-30 20:49
This issue can't be tested on version 4.3.2 due to not allowing Xamarin.Uitest to run on a physical device at all. See here for reference:
https://github.com/microsoft/appcenter/issues/2475#issuecomment-1774214848

**Comment by DmitriyKirakosyan** [comment] 2024-06-27 09:55
The initial issue was fixed, so I'm closing it.

**Closed by DmitriyKirakosyan** 2024-06-27 09:55 UTC
Labels: feature request, test, do-not-close
