### ISSUE TITLE
Failed to apply settings: push configuration is invalid.

### ISSUE THREAD

**Issue by charanjeet1997** [Microsoft/appcenter#290] opened 2019-04-05 06:59 UTC
Failed to apply settings: push configuration is invalid.

push notification server key is not accepting please give me slution

**Comment by Srki94** [comment] 2019-04-05 10:21
I'm having the same issue. 
Trying to set up Push service for Xamarin Android, during the last Step, after copying the Server key from Firebase project and clicking on the "Done" button, I get the following error : 
"Failed to apply settings: push configuration is invalid."

I'm following a step by step video tutorial for this.

**Comment by huynhduy1985** [comment] 2019-04-05 14:43
I'm having the same issue.

**Comment by lumaxis** [comment] 2019-04-05 15:39
Thanks for the reports! We're looking into this right now and will get back soon with an update.

**Comment by fabus1989** [comment] 2019-04-05 16:47
Same issue here #292

**Comment by Srki94** [comment] 2019-04-05 18:37
It seems that the issue is fixed now.

I had a chat with support earlier. It was confirmed that the issue was discovered and that fix was on the way.
Just checked now and the error is gone for me.

**Comment by lumaxis** [comment] 2019-04-05 19:09
@Srki94 Yes, we rolled back a deployment to mitigate the issue as quickly as possible. We're now looking into what exactly happened and how we can prevent it in the future.
Thanks for everybody's patience and letting us know about this!

**Comment by fabus1989** [comment] 2019-04-05 23:03
Yep, it's working. Thanks a lot :)

**Comment by lumaxis** [comment] 2019-04-05 23:06
Alright, since it seems to indeed have fixed people's issues, I'm going to close this. Thanks again!

**Closed by lumaxis** 2019-04-05 23:06 UTC
Labels: bug
