### ISSUE TITLE
"Something went wrong on our end" when viewing app crashes

### ISSUE THREAD

**Issue by danAtAllworx** [microsoft/appcenter#541] opened 2019-06-10 13:27 UTC
**What App Center service does this affect?**
Crash reporting using the HockeyApp WinForms SDK.

**Describe the bug**
I have a WinForms application that has been using HockeyApp for crash reporting for more than a year. When I try to view crashes for this application in App Center, I get a screen with the message "Something went wrong on our end". I can still view crash info for this app in HockeyApp.

**To Reproduce**
1. From All apps, click Interact for Windows
2. Click Diagnostics

**Expected behavior**
Able to view crash reports for the app

**Screenshots**
![SomethingWentWrong](https://user-images.githubusercontent.com/13766058/59198319-6f7c0c80-8b61-11e9-8b2b-bb9d46dd07de.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 74.0.3729.169

**Additional context**
This was my first attempt to view this information in App Center, so I have no historical information about whether or not it has worked in the past.

**Comment by winnieli1208** [comment] 2019-06-13 05:22
Hi @danAtAllworx - you're seeing this page because App Center doesn't currently support WinForms yet. I do think we can definitely improve our error message on this page, however, we're actively working on WinForms support and expect this to be complete around the end of July. 

I'm going to close this issue for now but I encourage you to follow our [iteration plan](https://github.com/Microsoft/appcenter/issues/466) to see our progress. I'll be sure to update this thread when we release as well. Thanks!

**Closed by winnieli1208** 2019-06-13 05:22 UTC
Labels: bug, diagnostics

**Comment by NavidV** [comment] 2021-05-05 06:56
Hi,
I have the same problem. I am using it for a xamarin forms application and it worked before. Just stoped working from almost week ago.

**Comment by Wufus** [comment] 2022-09-02 07:25
Same problem for all my UWP apps. The page refreshes endlessly and then shows "Something went wrong on our end".

**Comment by JanZeman** [comment] 2022-09-28 14:01
The same here. It has worked perfectly for the last 18 months or so. Today I refreshed the page while seeing one of the problem details and suddenly the whole Diagnostics / Issues section disappeared and got replaced with  "Something went wrong on our end" 😥

**Comment by JanZeman** [comment] 2022-09-28 14:03
Can the issue be re-opened, @winnie ?

**Comment by gaurakshay** [comment] 2022-09-29 14:24
Same issue for me (Xamarin.Forms)

**Comment by youzunFu** [comment] 2022-09-30 02:50
I have several Android app, only one app have same issue,It was still work for couple days ago.

**Comment by Sulando** [comment] 2022-09-30 05:20
Same issue here with a xamarin forms App for the android and the iOS part for a few days now. Worked perfectly for a long time before.

**Comment by andriy-grytsiv** [comment] 2022-09-30 09:56
For us the solution was quite peculiar one. You just need to change to change '30Days' to '28Days' in the link.

> errors?version=&appBuild=&period=last**30Days**&status=&errorType=all&sortCol=lastError&sortDir=desc to period=last**28Days**

It looks like AppCenter recently removed the filter "Last 30 days" and changed it to "Last 28 days". For each app your last serach filter is saved seoarately. So when you navigate to app you get saved filter for last 30 days, backend can't process it and displays error.

**Comment by JanZeman** [comment] 2022-09-30 10:04
Wow, that worked! Thank you so much for posting the solution, @andriy-grytsiv.
And your theory seems to be correct.
I just done what I should have done before I even posted here. I signed in on another (anonymous) browser where the service has not ran before. And there it also shows the 28 days by default.

Thank you :)

![image](https://user-images.githubusercontent.com/1670470/193246319-fb9a1887-1dd7-478e-a9c4-6b1131f36ab6.png)

**Comment by Sulando** [comment] 2022-09-30 10:13
@andriy-grytsiv Thank you that fixed the problem for me as well 👍 
Previously I used 90 days as my standard filter.

**Comment by mxstudios** [comment] 2022-10-03 13:04
That's insane. Obviously a bug. Thanks for posting this @andriy-grytsiv !

> For us the solution was quite peculiar one. You just need to change to change '30Days' to '28Days' in the link.
> 
> > errors?version=&appBuild=&period=last**30Days**&status=&errorType=all&sortCol=lastError&sortDir=desc to period=last**28Days**
> 
> It looks like AppCenter recently removed the filter "Last 30 days" and changed it to "Last 28 days". For each app your last search filter is saved separately. So when you navigate to app you get saved filter for last 30 days, backend can't process it and displays error.

**Comment by sikkemap** [comment] 2022-10-05 07:54
We have the same issue! I don't get it why the issue is closed if the bug is still there.

**Comment by dragnilar** [comment] 2022-10-10 18:36
@winnie  We were having this problem with app center as well. @mxstudios' work around got us past the error. This is something that you should address since it causes disruption and confusion. I could see this causing people who do not have the patience to search for a solution to get frustrated and quit using app center. :(

**Comment by giuseppenovielli** [comment] 2022-10-17 09:45
@andriy-grytsiv Thanks for workaround! 
@winnie Please fix, this bug. Thanks!
We have a lot of Xamarin's Forms App!

**Comment by AdamDiament** [comment] 2022-10-25 10:22
> Hi,
> I have the same problem. I am using it for a xamarin forms application and it worked before. Just stoped working from almost week ago.

I'm seeing this in a Xamarin Forms android app, today. Can confirm changing last90Days to last28Days works for me. @winnie/AppCenter team, surely this is a little one-line fix! Please can you investigate?

**Comment by dragnilar** [comment] 2022-10-26 21:03
I reported a bug in this within App Center since it seems @winnie is not responding. Also in all fairness to her, the problem we are talking about is completely different from the originally reported issue.

**Comment by chironexsoftware** [comment] 2022-10-27 15:52
Same issue for me @andriy-grytsiv solution worked.

**Comment by bmalumphy** [comment] 2022-12-07 04:51
This became an issue for our team on two of our deployed apps this past release.

**Comment by dragnilar** [comment] 2022-12-07 05:03
I received a response back from the app center team about this bug. They said they are working on fixing it and said to use the same work around  that @andriy-grytsiv posted up above (thanks again @andriy-grytsiv!).

**Comment by GivennameSurname** [comment] 2022-12-12 10:58
So this issue still occurs if you might have had a **Filter set **> 28 Days**** as mentioned @andriy-grytsiv 

@winnie - should be definitely Reopened and fixed on your Side as it is a Bug.

**Comment by dkaraush** [comment] 2023-04-11 08:17
Having this issue from yesterday on Android reports.
I'm not sure this is date filter related though. Looks like it caught some unsupported crash report, that breaks the whole page :(

**Comment by DanwithArduino** [comment] 2023-06-29 18:16
Still having this issue with a Xamarin.Forms app. Changing the url to 28days fixes the issue ¯\_(ツ)_/¯

**Comment by GivennameSurname** [comment] 2023-06-29 18:32
> Still having this issue with a Xamarin.Forms app. Changing the url to 28days fixes the issue ¯\_(ツ)_/¯

Unfortunately I can confirm that...

**Comment by jyndrkhole** [comment] 2023-10-18 07:28
I still facing the same issue for Android App and there is no way to filter the date range for the crash analytics.
<img width="1130" alt="Screenshot 2023-10-18 at 12 58 01 PM" src="https://github.com/microsoft/appcenter/assets/10459944/93323ae3-c585-4034-a0c1-348b74a44c0d">

**Comment by Aero9999** [comment] 2023-10-19 08:07
> I am still facing the same issue for Android App and there is no way to filter the date range for the crash analytics. <img alt="Screenshot 2023-10-18 at 12 58 01 PM" width="1130" src="https://user-images.githubusercontent.com/10459944/276144676-93323ae3-c585-4034-a0c1-348b74a44c0d.png">

Can you not edit it in the URL?

**Comment by jyndrkhole** [comment] 2023-10-19 08:10
Thanks, I edited the URL for 28 instead of 30 and it started showing the crash analytics on the tab!

**Comment by wagenheimer** [comment] 2023-10-26 18:03
I have encountered this problem as well. Changing the setting to 28 days manually fixed the issue for me, but this bug has been around for a long time. When will we get a permanent solution for it?

**Comment by Jiang-Junjie** [comment] 2023-12-18 03:40
> > Hi,
> > I have the same problem. I am using it for a xamarin forms application and it worked before. Just stoped working from almost week ago.
> 
> I'm seeing this in a Xamarin Forms android app, today. Can confirm changing last90Days to last28Days works for me. @winnie/AppCenter team, surely this is a little one-line fix / http redirect somewhere? Please can you investigate?

It works for me. I need to change the 90days to 28days in the link.
