### ISSUE TITLE
Add support for mac Catalyst

### ISSUE THREAD

**Issue by JuniperPhoton** [microsoft/appcenter#1578] opened 2020-01-16 04:36 UTC
**Describe the solution you'd like**

Currently AppCenter does not support mac Catalyst.

**Describe alternatives you've considered**

Discard AppCenter on my project, or use preprocessing marco to skip AppCenter on compiling mac Catalyst.

**Additional context**

![image](https://user-images.githubusercontent.com/7578386/72493753-cca91080-385c-11ea-8e6c-574749eca8ba.png)

**Comment by MatkovIvan** [comment] 2020-02-18 18:01
Duplicate of #1295

**Comment by galbraithjoseph** [comment] 2020-03-06 18:21
This is also blocking my use of mac catalyst.

**Comment by kevinzhow** [comment] 2020-03-24 02:55
Please add support to mac catalyst, I don't want to switch to Firebase.

**Comment by tualatrix** [comment] 2020-03-25 08:47
+1

Apple introduced Universal Purchase recently, and with macCatalyst technology, the apps from iOS platform support macOS can be adapted very easily. As a must-have crash/analytics tools, AppCenter should support macCatalyst at the first time.

https://developer.apple.com/support/universal-purchase/

**Comment by ahdbilal** [comment] 2020-03-25 10:43
Thank you all for voting on this feature. I will discuss this with the team and will circle back with an update.

**Comment by ahdbilal** [comment] 2020-03-27 18:32
We have added this feature in the backlog and the team plan to tentatively pick this up soon. I will share more details once the team starts working on it.

**Comment by jfahrenkrug** [comment] 2020-03-27 18:41
@ahdbilal Fantastic news, thanks so much!

**Comment by matthiaswenz** [comment] 2020-03-31 05:26
Mac Catalyst also has some interesting implications on our Diagnostics symbolication pipeline which we currently can't guarantee full support for.
That means: Until we address this, your Catalyst apps' crash reports will most likely be partially symbolicated. This is a known issue and we are looking into how it can be supported in the Diagnostics pipeline.

**Comment by lightbow** [comment] 2020-04-11 21:15
Even partial support would be great. Nevermind complete symbolication—it would be nice just to build for Catalyst without a linker error and have some bare-bones functionality.

**Comment by MatkovIvan** [comment] 2020-06-02 09:42
Hi there,
Mac Catalyst support for App Center Apple SDK has been [merged](https://github.com/microsoft/appcenter-sdk-apple/pull/2065) to `develop` branch, so you can already try it via SwiftPM. This will be included in the next SDK release. The feedback is always welcome.

Please note that this is only the client SDK part, so as @matthiaswenz mentioned, some things like symbolication is not fully working yet.

Thanks

**Comment by AlexStrugaru** [comment] 2020-10-12 13:49
Hi,
is there any support coming for Distribute also?

**Comment by jamztang** [comment] 2020-10-19 09:22
Hi, just wonder if there are any updates for the crash reports symbolication?

**Comment by snowpardx** [comment] 2020-10-20 09:36
@jamztang everything should work for mac Catalyst for a few months already sorry that it not stated explicitly here. Do you have any particular issues with Catalyst crash reports symbolication? If so I would recommend you to contact support via App Center portal so that it could be checked for particular case.

Cc @matthiaswenz

**Comment by MatkovIvan** [comment] 2020-10-20 10:43
@AlexStrugaru not yet. Also, please note that Distribute module doesn't support native macOS too.

Closing this issue as it was implemented and released some time ago.

**Closed by MatkovIvan** 2020-10-20 10:43 UTC
Labels: feature request, sdk

**Comment by konDeichmann** [comment] 2020-10-20 10:53
@MatkovIvan - The company I am working for used the distribution feature for all our Apps. Sadly we cannot migrate to catalyst Apps since it would mean to disable distribution.

This is **definitely** a flaw in the appcenter SDK - Therefore I think appcenter does not yet fully support Catalyst.

**Comment by MatkovIvan** [comment] 2020-10-20 12:54
@konDeichmann let's track this separately. It's not the same topic as the initial one.

**Comment by ZComwiz** [comment] 2020-12-04 19:01
Should add an ignore flag for Catalyst build until it's supported.

**Comment by olmisa** [comment] 2020-12-07 07:56
Hello @ZComwiz ,
Thanks for using App Center.
App Center already have Catalyst build support.
Thanks

**Comment by konDeichmann** [comment] 2020-12-07 07:59
Hello @olmisa,

So my iOS App will build for Mac (using Catalyst), if I use AppCenter Distribution?
Because last time I checked it won't even build

**Comment by MatkovIvan** [comment] 2020-12-07 13:15
@konDeichmann as I mentioned above, App Center SDK doesn't support Distribute module on macOS (including Catalyst). It's out of scope of Catalyst support, which was implemented a few months ago.

**Comment by konDeichmann** [comment] 2020-12-07 14:42
@MatkovIvan as far as I know I'm not able to deactivate (as an Example) Distribution for Mac, but keep it for iOS. Since it is not compiling on Mac I also have to remove it from ios to keep Catalyst support.

I understand that you don't want to support Distribution for Mac now - but there must be a better way to keep it into ios Apps and still support Catalyst?

**Comment by MatkovIvan** [comment] 2020-12-07 15:04
You can wrap distribute related code to
```swift
#if !targetEnvironment(macCatalyst)
```
or just
```swift
#if canImport(AppCenterDistribute)
```
You can look at [our test application](https://github.com/microsoft/appcenter-sdk-apple/blob/4.0.0/Sasquatch/SasquatchSwift/AppDelegate.swift#L81-L83) as an example. If you need help with it feel free to file separate issue or contact support on the portal.
