### ISSUE TITLE
[iOS] Distribute module crash with Analytics enabled

### ISSUE THREAD

**Issue by ufna** [Microsoft/appcenter#375] opened 2019-05-06 07:09 UTC
**What App Center service does this affect?**
Distibute + Analytics

**Describe the bug**
Similar to https://github.com/Microsoft/appcenter/issues/326 , but happens with Distribute module. Once app is launched it opens browser to login into AppCenter. After "in-app updates enabled" message it closes browser and crash occurs.

If Analytics module is disabled Distribute module works like a charm. Also, it works as it should on iPhone 7. 

**Expected behavior**
No crash.

**Smartphone (please complete the following information):**
 - Device: iPhone XS Max
 - OS: iOS 12.2
 - Version: 2.0.1

**Additional context**
SDK integration details: https://github.com/PushkinStudio/AppCenter-SDK-UE4/blob/develop/Source/AppCenter/Private/IOS/AppCenter_IOS.cpp#L39-L109

```
Thread 0 Crashed:
0   libsystem_kernel.dylib               0x00000001b71dc0bc __pthread_kill + 8
1   libsystem_c.dylib                    0x00000001b71351a8 abort + 140
2   libsystem_malloc.dylib               0x00000001b7230c84 malloc_vreport + 564
3   libsystem_malloc.dylib               0x00000001b7230e4c malloc_report + 60
4   libsystem_malloc.dylib               0x00000001b7222528 free + 428
5   libc++.1.dylib                       0x00000001b681eca0 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::reserve(unsigned long) + 260
6   Zen                                  0x0000000105021588 -[MSCrashes channel:didPrepareLog:internalId:flags:] (string:1471)
7   Zen                                  0x0000000104fecff4 -[MSChannelGroupDefault enumerateDelegatesForSelector:withBlock:] (MSChannelGroupDefault.m:89)
8   Zen                                  0x0000000104fed2d0 -[MSChannelGroupDefault channel:didPrepareLog:internalId:flags:] (MSChannelGroupDefault.m:104)
9   Zen                                  0x0000000104ffea58 -[MSChannelUnitDefault enumerateDelegatesForSelector:withBlock:] (MSChannelUnitDefault.m:512)
10  Zen                                  0x0000000104ffa3a0 -[MSChannelUnitDefault enqueueItem:flags:] (MSChannelUnitDefault.m:122)
11  Zen                                  0x000000010506248c -[MSDistribute sendFirstSessionUpdateLog] (MSDistribute.m:228)
12  Zen                                  0x00000001050684a4 -[MSDistribute openURL:] (MSDistribute.m:1063)
13  Zen                                  0x0000000105064d74 __61-[MSDistribute openURLInAuthenticationSessionWith:fromClass:]_block_invoke.458 (MSDistribute.m:593)
14  SafariServices                       0x00000001cc66e868 -[SFAuthenticationSession safariViewController:hostApplicationOpenURL:] + 160
15  SafariServices                       0x00000001cc6a8704 -[SFAuthenticationViewController remoteViewController:hostApplicationOpenURL:] + 108
16  SafariServices                       0x00000001cc6e4680 -[SFBrowserRemoteViewController willOpenURLInHostApplication:] + 76
17  CoreFoundation                       0x00000001b764f064 __invoking___ + 144
18  CoreFoundation                       0x00000001b752bbc8 -[NSInvocation invoke] + 320
19  libdispatch.dylib                    0x00000001b70598f4 _dispatch_client_callout + 16
20  libdispatch.dylib                    0x00000001b705cecc _dispatch_block_invoke_direct + 248
21  FrontBoardServices                   0x00000001ba042218 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 44
22  FrontBoardServices                   0x00000001ba041e94 -[FBSSerialQueue _performNext] + 432
23  FrontBoardServices                   0x00000001ba042490 -[FBSSerialQueue _performNextFromRunLoopSource] + 52
24  CoreFoundation                       0x00000001b75d7954 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
25  CoreFoundation                       0x00000001b75d78d0 __CFRunLoopDoSource0 + 88
26  CoreFoundation                       0x00000001b75d718c __CFRunLoopDoSources0 + 176
27  CoreFoundation                       0x00000001b75d1e60 __CFRunLoopRun + 984
28  CoreFoundation                       0x00000001b75d1764 CFRunLoopRunSpecific + 448
29  GraphicsServices                     0x00000001b980ddd4 GSEventRunModal + 104
30  UIKitCore                            0x00000001e452800c UIApplicationMain + 212
31  Zen                                  0x000000010584fd3c main (LaunchIOS.cpp:408)
32  libdyld.dylib                        0x00000001b7090ffc start + 0
```

**Comment by MatkovIvan** [comment] 2019-05-06 13:15
Duplicate of #326

**Closed by MatkovIvan** 2019-05-06 13:15 UTC
Labels: bug
