### ISSUE TITLE
Please have XCode 13.3 option available for the React Native IOS build process

### ISSUE THREAD

**Issue by vmarcel** [microsoft/appcenter#2409] opened 2022-04-01 20:39 UTC
**Describe the solution you'd like**
An option to select version 13.3 for XCode for React Native build configuration

**Describe alternatives you've considered**
I don't know any other alternatives unless I downgrade my version, but that will conflict with the other developer setup

**Additional context**
It is possible that the builds in App Center are failing for our Org because of that configuration difference

**Comment by DmitriyKirakosyan** [comment] 2022-04-12 05:20
Closing as duplicate of https://github.com/microsoft/appcenter/issues/2408.

**Closed by DmitriyKirakosyan** 2022-04-12 05:20 UTC
Labels: feature request
