### ISSUE TITLE
Tracking NSErrors

### ISSUE THREAD

**Issue by ivanicin** [microsoft/appcenter#1062] opened 2019-09-20 16:26 UTC
**Describe the solution you'd like**
An API like Microsoft.AppCenter.Crashes.Crashes.TrackError, but for native exceptions.

**Describe alternatives you've considered**
Right now you can raise exception when the NSError appears and then use standard logging, but if that is the only purpose of raising exception it feels like a wrong thing to do.

**Additional context**

**Comment by jwargo** [comment] 2019-09-20 17:22
@ivanicin thanks for this suggestion, I'll share this with the service PM.

**Comment by winnieli1** [comment] 2019-09-23 01:31
Thanks for the feature request! It sounds like you're looking for a way to log non fatal crashes (handled exceptions) for iOS apps? This isn't on our short term roadmap but is absolutely on our radar. I'll post here if I have any updates!

(Reference #192 for similar request)

**Comment by ivanicin** [comment] 2019-09-23 08:59
Yes I would say it is the same, just that issue doesn't contain any expected keywords in the title or even description (use logging like crashalitycs is not something everyone will be searching for).

**Comment by ivanicin** [comment] 2019-09-23 09:03
There is some difference though as I suggest logging of all native issues so it would include Java exceptions too. But the main purpose was for that NSError logging.

**Comment by MatkovIvan** [comment] 2020-04-07 12:54
Duplicate of #192

**Closed by MatkovIvan** 2020-04-07 12:54 UTC
Labels: diagnostics, feature request
