### ISSUE TITLE
Update URL for the App name when renaming the App name

### ISSUE THREAD

**Issue by CShri** [microsoft/appcenter#1249] opened 2019-10-22 16:07 UTC
I created a new entry in App center with name "App Name original". 

URL: 
https://appcenter.ms/orgs/owner-34z2/apps/App-Name-original/distribute/releases/1

Then I felt whatever App name I had used was wrong. So I updated the app detail by renamed the App title from "App Name original" to "App Renamed".

App name is updated. but the url still shows the old App name.

App Name is:  "App Renamed"

Expected URL - https://appcenter.ms/orgs/owner-34z2/apps/App-Renamed/distribute/releases/1

<img width="987" alt="Screenshot 2019-10-22 at 9 36 55 PM" src="https://user-images.githubusercontent.com/12253651/67306142-1dd28e00-f514-11e9-997e-32b7b664c9a0.png">

**Comment by Oddj0b** [comment] 2019-10-25 16:10
Duplicate of #1198

**Closed by Oddj0b** 2019-10-25 16:10 UTC
Labels: feature request
