### ISSUE TITLE
Custom crash for iOS

### ISSUE THREAD

**Issue by nectar1** [microsoft/appcenter#1731] opened 2020-03-06 07:45 UTC
I would like that App Center allows users to track errors by using handled exceptions for iOS.
In the same way like for Android 
https://docs.microsoft.com/en-us/appcenter/sdk/crashes/android#handled-errors

**Comment by winnie** [comment] 2020-03-11 19:37
Hi @nectar1 thanks for the feedback! Looks like this is a duplicate request for #192 . We don't have immediate plans to address this but I'll keep the issue updated when I have more details. Thanks!

**Comment by MatkovIvan** [comment] 2020-04-07 12:55
Duplicate of #192

**Closed by MatkovIvan** 2020-04-07 12:55 UTC
Labels: feature request
