### ISSUE TITLE
Duplicate custom events with same timestamp but different ingestion time in Application Insights

### ISSUE THREAD

**Issue by VaishaliGanesh** [microsoft/appcenter#2212] opened 2021-06-15 19:12 UTC
Hello,

I have created a custom events in Application Insights for tracking. However, I found few events are duplicated with the same timestamp and operation ID but only the ingestion time differs. It seems there could be some intermittent issues on the ingestion of ApplicationInsights that create this duplication. But it does not seem to be constant and is related to specific incidents.

Please let me know to resolve this issue.

Thanks in advance.

**Comment by DmitriyKirakosyan** [comment] 2021-06-15 20:35
Duplicate of https://github.com/microsoft/appcenter/issues/1314.

Please reopen the issue if you feel your case is different.
Closing.

**Closed by DmitriyKirakosyan** 2021-06-15 20:35 UTC
Labels: analytics, feature request

**Comment by VaishaliGanesh** [comment] 2021-06-16 13:31
Please reopen the issue as I am unable to do and the case is different and related to Application Insights
