### ISSUE TITLE
Add support for API token on organization / company level

### ISSUE THREAD

**Issue by svendr** [microsoft/appcenter#2402] opened 2022-03-24 09:13 UTC
**Describe the solution you'd like**
API tokens are currently defined either as user tokens or as app tokens. There's no option to define an API token on a company / organization level. These would provide a reasonable scope / usability, meaning they would be valid for all apps of a specific orga, but not all apps of all orgas (like user tokens). And they could use organization level distribution groups (which app level tokens can't).

**Describe alternatives you've considered**
User tokens are no good solution:
* their are bound to a specific user; if that user leaves the company or his/her account is removed from the orga, the corresponding tokens stop to work
* their are valid for all apps of all organizations the user is a member of

App tokens are no good solution either:
* they have to be defined per app, which gets cumbersome if there are many apps per orga or just many different flavours of an app
* they can't use organization level distributions groups, so you'd have to re-define distribution groups with copy- and paste for each app

This feature has already been requested in #1459 but this issue got auto-closed.

**Comment by lucen-ms** [comment] 2022-03-31 11:44
Closing as duplicate of #1459. Please use it for any further discussion.

**Closed by lucen-ms** 2022-03-31 11:44 UTC
Labels: feature request, account
