### ISSUE TITLE
Trying to add tag from appcenter's build script

### ISSUE THREAD

**Issue by shibathethinker** [microsoft/appcenter#848] opened 2019-08-09 07:34 UTC
**What App Center service does this affect?**
appcenter pre-build and post-build scripts

**Describe the bug**
I am trying to  to push git tag from appcenter build script. It does not seem to allow me.

**To Reproduce**
Write -

   git tag  'test'
   git push origin 'test'

Error:
fatal: could not read Password for {username}: terminal prompts disabled

I have tried adding ssh key file through the script and also tried to set password from script.
Neither works.
I was expecting something like this should exist for appcenter -

https://github.com/semantic-release/semantic-release/blob/master/docs/03-recipes/git-auth-ssh-keys.md

**Expected behavior**
Should allow to push tag successfully

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nrajpurkar** [comment] 2019-08-23 01:08
Hi @shibathethinker, is this a duplicate of this [issue](https://github.com/microsoft/appcenter/issues/23)?

**Comment by phoney** [comment] 2020-07-15 21:58
This issue isn't a duplicate of that other issue. This issue is asking how to tag a build and push the tag to the original repo. That other issue is asking how to build from an existing tag.

**Comment by stephan-markovic** [comment] 2022-07-01 05:38
This custom action is not supported.

**Closed by stephan-markovic** 2022-07-01 05:38 UTC
Labels: bug, build, reviewed-DRI
