### ISSUE TITLE
Build for React Native Android - new step/task "Running jetifier" (AndroidX, React-Native 0.60)

### ISSUE THREAD

**Issue by alexander-w-o-s** [microsoft/appcenter#887] opened 2019-08-14 10:00 UTC
**Describe the solution you'd like**
Add new step/task "Running jetifier" in App Center Build services for React Native Android.

React Native 0.60 has been migrated over to AndroidX.
This is a breaking change that makes impossible using App Center Build for React Native Android without additional configuration.

Official React Native blog post about AndroidX breaking change in React Native 0.60 - https://facebook.github.io/react-native/blog/2019/07/03/version-60#androidx-support

`react-native run-android` command now runs jetifier automatically:
https://github.com/react-native-community/cli/blob/master/packages/platform-android/src/commands/runAndroid/index.ts#L70

This automatic jetifier run in react-native cli makes ambiguous why App Center Build service doesn't work for React Native Android.

**Describe alternatives you've considered**
Create `appcenter-pre-build.sh` script with following content:
```
#!/usr/bin/env bash
node node_modules/jetifier/bin/jetify
```

**Additional context**
This is important only when React Native project uses react-native modules that are not migrated to AndroidX yet.
Examples of such modules (2019-08-14):
- react-native-reanimated (https://github.com/kmagiera/react-native-reanimated/issues/337)
- react-native-vector-icons (https://github.com/oblador/react-native-vector-icons/issues/930)

**Comment by YajanaRao** [comment] 2019-08-19 12:24
Any update on this issue ?

**Comment by nrajpurkar** [comment] 2019-08-23 01:05
Hi there, we're taking a look at this issue and working on a solution at the moment! Thanks for your patience!

**Comment by max-lobanov** [comment] 2019-08-27 05:38
Hello everyone, fix for this issue was shipped recently. Could you please re-save build configuration and run a new build to validate that everything works for you?

**Comment by alexander-w-o-s** [comment] 2019-08-27 14:32
@max-lobanov, everything works good. Thank you!

**Comment by max-lobanov** [comment] 2019-08-27 14:50
Great!
I am closing the issue, please let me know if you have any questions

**Closed by max-lobanov** 2019-08-27 14:50 UTC
Labels: build, feature request

**Comment by a-sane** [comment] 2019-12-30 13:51
Looks like Run Jetify task disapear from appcenter a few days ago

**Comment by DennisPan** [comment] 2020-01-06 23:15
@a-sane What React Native version are you using?

**Comment by a-sane** [comment] 2020-01-07 08:06
@DennisPan 0.61.5

**Comment by DennisPan** [comment] 2020-01-08 00:13
@a-sane That should work. Could you reach out to support (via the portal)? That'll allow us to collect your app details and look further

**Comment by addingama** [comment] 2020-01-08 06:51
@DennisPan I also have the same problem since today.

jetify task not running

**Comment by DennisPan** [comment] 2020-01-09 23:52
@addingama Our team tried couple test applications and couldn't reproduce. Do you mind also reaching out to support for us to take a deeper look?

**Comment by olethanh** [comment] 2020-01-20 15:53
We  had the same problem since two weeks ago. I repushed the branch under a new name and it's working again. Not great

**Comment by artemkhalygov** [comment] 2020-04-15 16:12
@DennisPan Two days ago everything was good, but now jetify task not running. React Native v0.62.2

**Comment by DennisPan** [comment] 2020-05-06 19:00
@artemkhalygov Please reach out to support so we can take a deeper look.

**Comment by bramski** [comment] 2020-10-08 21:34
Not working for me today either. React Native 0.63.0.
package.json has 
```
"postinstall": "npx jetify",
```
and I setup an `appcenter-pre-build.sh` as was suggested above. still failing.

**Comment by yasirtrimulabs** [comment] 2021-01-15 19:31
Everything was working fine but today it just happened.  I setup an `appcenter-pre-build.sh` as was suggested by @alexander-w-o-s and it finally worked Thanks. 
But this issue should not be recurring and that too out of nowhere.

**Comment by yasirtrimulabs** [comment] 2021-05-04 21:28
**UPDATE**:
I think this issued should be re opened, as I am facing this same issue today again. 
I added the command in `appcenter-pre-build.sh` a few months ago, and today out of nowhere I am facing this issue again. I tried to make a build in local machine and ran the `jetify` command and it's working on local.

**Comment by carlosmen-hrbl** [comment] 2021-05-04 21:39
Seems that jetifier decided to add some extra messages that might be breaking builds:
https://github.com/react-native-community/cli/issues/1409

**Comment by mikehardy** [comment] 2021-05-04 22:02
Fix your dependencies - that is take the messages into account by proposing PRs to the few straggling modules or use patch-package to fix them locally - at some point jetifier needs to sunset, so far with one day live it appears react-native-track-player and...no other module people have reported are left as stragglers. Close to the finish line on jetifier it just needs your help to fix the final module(s) your app depends on

**Comment by mikehardy** [comment] 2021-05-04 22:07
It appears the console.warn's I added are mapped to stderr somehow? 
https://github.com/mikehardy/jetifier/commit/a027dd065c62e19af29afe19e500391b62d39847

That should not happen, and I believe `--no-jetifier` is the invocation argument for the react-native CLI to not invoke jetifier at all, avoiding all warnings (assuming your project no longer needs jetifier!)

Hope this helps

**Comment by stefoid** [comment] 2021-05-05 00:49
![Screen Shot 2021-05-05 at 10 49 24 am](https://user-images.githubusercontent.com/8017974/117086318-9532e000-ad8f-11eb-82a1-9208d416b703.png)

**Comment by mikehardy** [comment] 2021-05-05 03:51
Well, today I learned emitting something on console.warn is a breaking change. Honestly shocked about that.

I issued jetifier@1.6.8 that is equivalent to 1.6.6, no console.warn deprecation.

I am going to re-issue the deprecation notice, but if it's a breaking change okay - it'll go out as 2.0. If AppCenter still breaks at that point at least I was trying semver...

**Comment by stefoid** [comment] 2021-05-05 04:07
you are a saint

thx!

**Comment by Arkan4ik** [comment] 2022-04-19 21:55
@mikehardy I am using 2.0.0 jetifier but have the same problem as author of this issue. Could you help please?

**Comment by mikehardy** [comment] 2022-04-19 23:15
@Arkan4ik as far as I can tell this has nothing to do with me anymore. If you need jetifier to work still, with no console.warns, use v1.x. If you want the deprecation notice, use 2.x

But in my firm opinion, my own software should never be used by anyone anymore. AndroidX conversion is or should be complete and the `--no-jetifier` tag should be used at all times, in combination with current versions of software

I'm not personally going to spend any more time on AndroidX transition for that reason. The transition is over

**Comment by Arkan4ik** [comment] 2022-04-23 19:49
@mikehardy 1.68 version solved my problem, thank you. I will take a look to get rid of jetifier
