### ISSUE TITLE
Platform does not match error when uploading an Android app to App-Center

### ISSUE THREAD

**Issue by golanshy** [microsoft/appcenter#954] opened 2019-08-28 10:24 UTC
I'm trying to upload an Android app to a new Organisation and I get the following error:
{"status"=>"error", "message"=>"Platform does not match. Expected value: iOS. Actual value: Android."}
The organisation has no apps yet and I couldn't find anything in the settings to tell it's an iOS only (We wish it to be both Android & iOS)
Appreciate your help.

appcenter_upload(
api_token: ENV["APPCENTER_API_TOKEN"],
owner_name: ownerName,
owner_type: "organization",
app_os: 'Android',
app_platform: 'Java',
app_name: appName,
apk: "./outputs/apksV5.x.x/" + filename,
notify_testers: true
)

**Comment by nrajpurkar** [comment] 2019-08-30 00:08
thanks for the issue @golanshy, is this when using the fastlane plugin?

**Comment by golanshy** [comment] 2019-08-30 08:02
Yes, when using the fastlane plugin

**Comment by nrajpurkar** [comment] 2019-08-30 17:42
Thanks for clarifying! We're taking a deeper look at this.

**Comment by evkhramkov** [comment] 2019-08-30 17:47
@golanshy we already have a ticket from you about this https://github.com/microsoft/fastlane-plugin-appcenter/issues/111

Have you reached out to our support? Also take a look at this comment, maybe it is the same case https://github.com/microsoft/fastlane-plugin-appcenter/issues/111#issuecomment-526215976

**Comment by evkhramkov** [comment] 2019-08-30 17:48
I'm closing this as a duplicate of https://github.com/microsoft/fastlane-plugin-appcenter/issues/111

**Closed** 2019-08-30 17:56 UTC
Labels: feature request
