### ISSUE TITLE
Android app insights User Flow Visualization--one Event shows multiple times

### ISSUE THREAD

**Issue by rajiniyadav** [microsoft/appcenter#2432] opened 2022-06-20 07:34 UTC
I have using appcenter analytics in my Android application, but when we try User Flows in Application Insights on Azure the same event shows multiple times.

Could you help me out why the event shows multiple time.

Please refer below screenshot
![Uploading Capture.PNG…]()

**Comment by aleksandr-dorofeev** [comment] 2022-06-21 11:24
Hello @rajiniyadav 
Looks like a duplicate of https://github.com/microsoft/appcenter/issues/1314.

Please reopen the issue if you feel your case is different.
Closing.

**Closed by aleksandr-dorofeev** 2022-06-21 11:25 UTC
Labels: feature request, analytics
