### ISSUE TITLE
Trigger new build when a pull request is created

### ISSUE THREAD

**Issue by CJ99** [microsoft/appcenter#438] opened 2019-05-17 21:12 UTC
**Describe the solution you'd like**
I would like to trigger a build when a pull request is created in the code repository and send the notification to the developer about the build status. 

**Describe alternatives you've considered**
Currently, we can only set up a build with the specific branch in App Center, but not configure a build for the pull request. It will be much helpful to have the confidence to merge the pull request after build. 

**Additional context**
Most of online CI products have supported this feature. I hope AppCenter can support it as well.

**Comment by nrajpurkar** [comment] 2019-06-05 13:57
@CJ99 thanks for this request. I'm closing this as it is a duplicate of #159

**Closed by nrajpurkar** 2019-06-05 13:57 UTC
Labels: build, feature request
