### ISSUE TITLE
Currently AppCenter only supports Appium tests written in java. How about ones written in .NET

### ISSUE THREAD

**Issue by SOFSPEEL** [microsoft/appcenter#1379] opened 2019-11-16 18:03 UTC
To be able to run Appium tests written in .Net, currently only java appium tests are supported

**Comment by Oddj0b** [comment] 2019-11-19 15:07
I think this is a duplicate of #102. If I'm correct, remember to vote else re-open this issue.

**Closed by Oddj0b** 2019-11-19 15:07 UTC
Labels: feature request, test
