### ISSUE TITLE
Audit page

### ISSUE THREAD

**Issue by anivaros** [microsoft/appcenter#1508] opened 2019-12-18 16:02 UTC
**Describe the solution you'd like**
Audit page with all actions in account. Who and when added/deleted app, added user, build, etc.

**Additional context**
We are can't find multiple apps in our organisation account, looks like someone deleted them. It would be nice to have page where we can find info about actions like that.

Screenshot from TeamCity with same functionality:
![Screenshot 2019-12-18 at 19 04 51](https://user-images.githubusercontent.com/873387/71102321-55cf1800-21c9-11ea-85d1-29b653dc1347.png)

**Comment by alexcnichols** [comment] 2019-12-18 21:26
Hi @anivaros - Thanks for reaching out. That could be confusing when something like an app completely disappears. An audit screen could help pin down what happened. I also wonder whether tightening the permissions to be able to create/delete apps in your organization or establishing a clearer process around it could help. I found a related issue discussing audit, which I'll close and reference this into for more information as use cases, options, and priority is considered. 

Duplicate of #1485

**Closed by alexcnichols** 2019-12-18 21:26 UTC
Labels: account, feature request
