### ISSUE TITLE
Strong Sign the assemblies (in nugets)

### ISSUE THREAD

**Issue by NunoPeixotoPrimavera** [microsoft/appcenter#1125] opened 2019-10-02 14:12 UTC
For those who have strong signed applications is necessary to have strong signed dependencies, so this is a problem for us. 
You could even make a version of strong signed nugets available, and one as it currently exists

**Comment by botatoes** [comment] 2019-10-02 20:46
Hi, thanks for the feature request. Can you please explain a little bit more what you would expect for the solution?

**Comment by NunoPeixotoPrimavera** [comment] 2019-10-02 21:24
Hi, it's very simple. Sign the assemblies with SNK in the nuget packages.

**Comment by WaivedAnswer** [comment] 2020-03-06 19:15
@NunoPeixotoPrimavera this request seems to have received more traction #1321

**Comment by MatkovIvan** [comment] 2020-12-28 08:50
Hi there. Let's track this feature request in #1321, I know this one was opened a bit early, but anyway.

Duplicate of #1321

**Closed by MatkovIvan** 2020-12-28 08:50 UTC
Labels: feature request
