### ISSUE TITLE
Builds failing randomly with SQLite error

### ISSUE THREAD

**Issue by HarlowBurgess** [microsoft/appcenter#847] opened 2019-08-08 17:03 UTC
**What App Center service does this affect?**
Build

**Describe the bug**
Builds failing randomly over the past several days with SQLite error code:6922, 'disk I/O error'. Resubmitting the exact same build over again, or performing another code push, works on the second try.

**To Reproduce**
1. Push to a branch with automated builds enabled
2. Automated build fails with SQLite error code:6922, 'disk I/O error'.
3. Make another push or perform a manual build
4. Automated build succeeds

**Expected behavior**
Valid builds to complete successfully.

**Screenshots**
error : CoreData: error: (6922) I/O error for database at /Users/vsts/Library/Developer/Xcode/UserData/IB Support/Simulator Devices/08C713DA-B9AF-4028-A13B-1077E4C4B57F/data/tmp/Untitled-v8TjRg50.uicatalog.  SQLite error code:6922, 'disk I/O error' [/Users/vsts/agent/2.155.1/work/1/s/...iOS.csproj]

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Build is for a Xamarin Forms iOS build.

**Comment by Foovanadil** [comment] 2019-08-08 21:40
We are also seeing this same issue with our iOS builds. Does anybody have thoughts?

**Comment by EdwardRushDeveloper** [comment] 2019-08-09 17:34
We are also getting the same error in Azure DevoOps

obj/iPhone/Release/actool/cloned-assets/Assets.xcassets : error : CoreData: error: (6922) I/O error for database at /Users/vsts/Library/Developer/Xcode/UserData/IB Support/Simulator Devices/33642807-6BA9-41FB-893D-9FCB619A253A/data/tmp/Untitled-T3cwodDk.uicatalog.

**Comment by rj-thomas** [comment] 2019-08-10 03:15
We also have this issue with Xamarin iOS apps that previously built fine

**Comment by Ysquare63** [comment] 2019-08-12 18:42
We are also getting the same error in Azure DevOps

obj/iPhone/Release/actool/cloned-assets/Assets.xcassets : error : CoreData: error: (6922) I/O error for database at /Users/vsts/Library/Developer/Xcode/UserData/IB Support/Simulator Devices/33642807-6BA9-41FB-893D-9FCB619A253A/data/tmp/Untitled-T3cwodDk.uicatalog.

**Comment by barryculhane** [comment] 2019-08-13 05:17
Getting the exact same type of error as reported by @Ysquare63 in Azure DevOps - iOS builds that worked fine yesterday are failing consistently today.  No code changes.

My build pipeline has two iOS build tasks (A & B) for two different flavors of an app - sometimes A fails and B succeeds, sometimes the other way around, sometimes both fail, never do both succeed. 
 Very frustrating!

**Comment by DennisPan** [comment] 2019-08-13 05:31
Could you reach out to support via App Center portal, so that we can collect a few more details? Would like to pick couple apps for a deeper look.

**Comment by barryculhane** [comment] 2019-08-13 06:07
@DennisPan I started a conversation in App Center, and the bot responded saying App Center usually responds within a day.  Just to be clear, I'm not having this issue through App Center, I'm using Azure DevOps.

**Comment by DennisPan** [comment] 2019-08-13 06:14
@barryculhane Thanks for doing that! I won't be able to collect more information from your Azure DevOps builds, as I don't have access there. There were other customers hitting the same in our support tickets, so I have something to start with, for now. 

I assume you are using Hosted Mac images in Azure DevOps? App Center team produces those, so you've still reached out to the right place from that perspective 😄

**Comment by barryculhane** [comment] 2019-08-13 06:43
@DennisPan Yes, we're using the Hosted Mac OS agent.  I uploaded the logs ZIP from one of the failed builds, if that helps.  Thanks for the speedy response.

**Comment by vecalion** [comment] 2019-08-13 10:56
> Could you reach out to support via App Center portal, so that we can collect a few more details? Would like to pick couple apps for a deeper look.

We're experiencing the same issue with App Center builds. I initiated a conversation App Center.

**Comment by barryculhane** [comment] 2019-08-13 16:05
@DennisPan The issue appears to have been resolved in Azure DevOps, have successfully queued two different builds without any issues. Thanks for your assistance!

**Comment by DennisPan** [comment] 2019-08-13 16:09
@barryculhane hmmm.... we haven't really found the root cause yet. Let's keep an eye on this given this seems to happen intermittently. Would love to hear from others as well if things start to turn better than before.

**Comment by HarlowBurgess** [comment] 2019-08-13 23:25
Worse actually. Now happening much more often. Last 4 builds failed. Looks like @Ysquare63 reported this issue on the same file as us: "Assets.xcassets".

Here is more detail:

"/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/<project>.iOS.csproj" (Rebuild target) (1) ->
(_CoreCompileImageAssets target) -> 
  /Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/obj/iPhone/AppCenter/actool/cloned-assets/Assets.xcassets : error : CoreData: error: (6922) I/O error for database at /Users/vsts/Library/Developer/Xcode/UserData/IB Support/Simulator Devices/624FF352-CAB5-4F1D-9D47-FBE8DE0EFD59/data/tmp/Untitled-CG3HiQu3.uicatalog.  SQLite error code:6922, 'disk I/O error' [/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/<project>.iOS.csproj]
/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/obj/iPhone/AppCenter/actool/cloned-assets/Assets.xcassets : error : CoreData: error: SQLCore dispatchRequest: exception handling request: <NSSQLFetchRequestContext: 0x7f99908cf670> , I/O error for database at /Users/vsts/Library/Developer/Xcode/UserData/IB Support/Simulator Devices/624FF352-CAB5-4F1D-9D47-FBE8DE0EFD59/data/tmp/Untitled-CG3HiQu3.uicatalog.  SQLite error code:6922, 'disk I/O error' with userInfo of { [/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/<project>.iOS.csproj]
/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/obj/iPhone/AppCenter/actool/cloned-assets/Assets.xcassets : error :     NSFilePath = "/Users/vsts/Library/Developer/Xcode/UserData/IB Support/Simulator Devices/624FF352-CAB5-4F1D-9D47-FBE8DE0EFD59/data/tmp/Untitled-CG3HiQu3.uicatalog"; [/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/<project>.iOS.csproj]
/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/obj/iPhone/AppCenter/actool/cloned-assets/Assets.xcassets : error :     NSSQLiteErrorDomain = 6922; [/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/<project>.iOS.csproj]
/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/obj/iPhone/AppCenter/actool/cloned-assets/Assets.xcassets : error : } [/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/<project>.iOS.csproj]
/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/obj/iPhone/AppCenter/actool/cloned-assets/Assets.xcassets : error : CoreData: error: -executeRequest: encountered exception = I/O error for database at /Users/vsts/Library/Developer/Xcode/UserData/IB Support/Simulator Devices/624FF352-CAB5-4F1D-9D47-FBE8DE0EFD59/data/tmp/Untitled-CG3HiQu3.uicatalog.  SQLite error code:6922, 'disk I/O error' with userInfo = { [/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/<project>.iOS.csproj]
/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/obj/iPhone/AppCenter/actool/cloned-assets/Assets.xcassets : error :     NSFilePath = "/Users/vsts/Library/Developer/Xcode/UserData/IB Support/Simulator Devices/624FF352-CAB5-4F1D-9D47-FBE8DE0EFD59/data/tmp/Untitled-CG3HiQu3.uicatalog"; [/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/<project>.iOS.csproj]
/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/obj/iPhone/AppCenter/actool/cloned-assets/Assets.xcassets : error :     NSSQLiteErrorDomain = 6922; [/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/<project>.iOS.csproj]
/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/obj/iPhone/AppCenter/actool/cloned-assets/Assets.xcassets : error : } [/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/<project>.iOS.csproj]
/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/obj/iPhone/AppCenter/actool/cloned-assets/Assets.xcassets : error : 2019-08-13 23:08:37.933 IBCocoaTouchImageCatalogTool[893:6384] asset import didn't finish Got exception *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0] [/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/<project>.iOS.csproj]
  /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets(1218,3): error : actool exited with code 1 [/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/<project>.iOS.csproj]
  /Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/obj/iPhone/AppCenter/actool/cloned-assets/Assets.xcassets : actool error : Exception Raised during asset import (2) [/Users/vsts/agent/2.155.1/work/1/s/<project>/<project>.iOS/<project>.iOS.csproj]

**Comment by shahmirn** [comment] 2019-08-14 03:16
We're also seeing the same error. Last three builds failed 'cause of SQLite error.

**Comment by DennisPan** [comment] 2019-08-14 06:03
Quick update - this is still under investigation. We are testing rolling back recent changes and see if that removes the intermittent failures.

**Comment by JuliusH93** [comment] 2019-08-14 07:47
Same problem here in DevOps Pipeline for our Xamarin.iOS Build.
The first build failing with this error was at 31.7.2019, 16:26:31.

obj/iPhone/Debug/actool/cloned-assets/Assets.xcassets : error : CoreData: error: (6922) I/O error for database at /Users/vsts/Library/Developer/Xcode/UserData/IB Support/Simulator Devices/D4160B7E-E418-4671-B6B2-F9015471F3A3/data/tmp/Untitled-Loih3S2i.uicatalog.  SQLite error code:6922, 'disk I/O error'

**Comment by DennisPan** [comment] 2019-08-14 15:06
For folks who have been running into this, I'd appreciate if you can give this a try:

1. Add post clone script in your repo: https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/#post-clone
2. Add `xcrun simctl erase all` in the script
3. Re-save the branch configuration so that the script gets picked up
4. Queue a new build

This fixed a similar issue from [other users](https://stackoverflow.com/questions/42308361/ios-10-core-data-exception-code-error-6922) who installed Xcode 11 beta, which we have on the images.

**Comment by jfversluis** [comment] 2019-08-15 09:47
@DennisPan I have talked to a customer who had this problem and recommended this solution. It seems to work for him.

**Comment by DennisPan** [comment] 2019-08-15 17:19
Great - thanks @jfversluis !

For everyone who have been getting this intermittent failures, if you are still seeing it (with or without the workaround above), please let me know. We've shipped a new image which potentially improves the case here. Would appreciate to know how things are working for everyone, especially if you don't apply the workaround above.

**Comment by HarlowBurgess** [comment] 2019-08-16 00:27
Still failing with same error. Now failing every time. 7 failed builds in a row.

**Comment by DennisPan** [comment] 2019-08-16 00:48
@HarlowBurgess Is that with or without the [workaround](https://github.com/microsoft/appcenter/issues/847#issuecomment-521286394)? Could you also reach out to support so that we can take a deeper look at your builds?

**Comment by HarlowBurgess** [comment] 2019-08-16 05:12
Without workaround. All iOS builds continue to fail. Not sure how to reach out to support. The docs at https://docs.microsoft.com/en-us/appcenter/general/support-center say to go to this GitHub (which I have done) or to "click on the **Contact us** option in the question menu on the top right of the portal page", only such an option does not exist.

**Comment by DennisPan** [comment] 2019-08-16 05:17
@HarlowBurgess Could you give the workaround a try? 

As for support, on the same page you linked:
>To get help on any issue you may experience, use the blue chat button at the bottom-right corner of every App Center portal page. Alternatively, click on the Contact us option in the question menu on the top right of the portal page.

**Comment by HarlowBurgess** [comment] 2019-08-16 05:43
The workaround was successful. Thanks!

> For folks who have been running into this when running builds in App Center, I'd appreciate if you can give this a try:
> 
> 1. Add post clone script in your repo: https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/#post-clone
> 2. Add `xcrun simctl erase all` in the script
> 3. Re-save the branch configuration so that the script gets picked up
> 4. Queue a new build
> 
> For Azure DevOps users, you can add a Shell script task and run the same command.
> 
> This fixed a similar issue from [other users](https://stackoverflow.com/questions/42308361/ios-10-core-data-exception-code-error-6922) who installed Xcode 11 beta, which we have on the images.

**Comment by JuliusH93** [comment] 2019-08-19 13:40
The workaround works here too, directly per command line in our DevOps pipeline. Thanks!

> For folks who have been running into this when running builds in App Center, I'd appreciate if you can give this a try:
> 
> 1. Add post clone script in your repo: https://docs.microsoft.com/en-us/appcenter/build/custom/scripts/#post-clone
> 2. Add `xcrun simctl erase all` in the script
> 3. Re-save the branch configuration so that the script gets picked up
> 4. Queue a new build
> 
> For Azure DevOps users, you can add a Shell script task and run the same command.
> 
> This fixed a similar issue from [other users](https://stackoverflow.com/questions/42308361/ios-10-core-data-exception-code-error-6922) who installed Xcode 11 beta, which we have on the images.

**Comment by chrisstaley** [comment] 2019-08-19 15:19
@DennisPan My build failed three times in a row, and then I tried the workaround. It worked.

**Comment by DennisPan** [comment] 2019-08-19 17:02
Thanks for giving this a try and sharing the results everyone! We are rolling out a new image with this, after which you can remove the script in your repository.

**Comment by jennablackwell** [comment] 2019-08-19 18:36
Same here - had the build failures then did the workaround and it worked

**Comment by Ysquare63** [comment] 2019-08-19 18:49
Work around worked around.  Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by bryansmi** [comment] 2019-08-21 16:44
Hello! We've rolled out a new image for our macOS VMs which should resolve this issue. We'd love to hear if building without the workaround is fixed now. Thanks.

**Comment by battepatikiran** [comment] 2019-08-22 22:07
When does the new macOS VMs are updated ? it still shows as Date: 2019-08-09 13:12:18 on my Azure DevOps agents.

**Comment by bryansmi** [comment] 2019-08-22 22:44
Azure DevOps agents you provision yourself will not be affected by this change. These images are deployed to the Hosted macOS agents, which are specifically provisioned for App Center.

If you have a branch configured for Build on App Center, and were seeing this issue previously, you should be able to run a new build successfully now. Hopefully that makes sense!

**Comment by mikehachen** [comment] 2019-08-26 07:17
This solution worked for me (AppCenter Build)

**Comment by DennisPan** [comment] 2019-10-11 07:13
We haven't seen this for a while, so I'm closing this out. Feel free to reach out if you see more of this.

Appreciate everyone for letting us know you ran into this, giving us the patience and trying the workaround!

**Closed by DennisPan** 2019-10-11 07:13 UTC
Labels: bug, build
