### ISSUE TITLE
Manual set version number

### ISSUE THREAD

**Issue by Moccassins** [microsoft/appcenter#1004] opened 2019-09-10 12:35 UTC
Hi there.

We had splitted our WPF project in several nuget packages that share a common library containing our version number. In HockeayApp, we set the version number by retreving it manualy from the shared library. This way, we don't have to build our main application, if we just updated one of our sub projects. Unfortunable we didnt found a way to set the version number manualy with AppCenter like we did in hockey. Can you give us a hint or implement a similar option for these target?

Greetings
Daniel

**Comment by elamalani** [comment] 2019-09-10 16:08
@Moccassins We will look into your question and someone from the team will reach out to you soon.
Thanks!

**Comment by winnieli1** [comment] 2019-09-11 14:57
Hi @Moccassins - are you looking for a way to set a version number when making a release? If you upload a .zip or .msi package to App Center, you should see an input field for you to manually set the version number. Is that what you're referring to?

Thanks!

**Comment by Moccassins** [comment] 2019-09-12 05:55
No, we dont upload anything. We want to set the current version that is reported by a crash report from c# code at runtime.

**Comment by Moccassins** [comment] 2019-09-16 06:39
anything new?

**Comment by winnieli1** [comment] 2019-09-23 01:51
Hi @Moccassins - apologies for the delay. I'm not sure I completely understand your request. Are you looking for a way to manually upload crash logs and then set the version for those logs?


If not, can you send a screenshot or walk me through the steps you're going through in HockeyApp? I appreciate it!

**Comment by Moccassins** [comment] 2019-09-26 05:27
We developed our own way to send our data to HockeApp. With that method, we could change the Version number at runtime like we want. Currently, using the AppCenter SDK there is no way to change the Version number manualy, as i can see, it uses allways the file version. We want to set the Version number to use manual on app startup. For this, we need some method to call at app startup or an extra method parameter. Maybe in the Method AppCenter.Start. It could look like: AppCenter.Start("secret app key", typeof(Analytics), typeof(Crashes), version: "1.2.3.4");
This topic needs to be handled by the AppCenter SDK developers.

**Comment by winnieli1** [comment] 2019-10-10 16:45
Hi @Moccassins - just checked with the SDK team and confirmed we don't currently support this scenario. I'll label this issue as a feature request and keep it open to track community interest. 

Thanks!

**Comment by dragnilar** [comment] 2020-03-02 18:44
@winnie  I second this request. We currently don't use the app center for distribution since we push our releases to an Azure storage blob, but we still use the app center for crash reports. It would be nice to be able to set the version number without having to manually upload an MSI or add another release step to our pipeline.

**Comment by nathanjeynes** [comment] 2020-04-29 16:52
We would aslo find it useful to be able to call something like AppCenter.setVersionID manually.

**Comment by MatkovIvan** [comment] 2020-05-20 09:05
Looks like it's duplicate of #1313

Let's track this feature request there

**Closed by MatkovIvan** 2020-05-20 09:05 UTC
Labels: diagnostics, feature request
