### ISSUE TITLE
Webhook For Test Completion

### ISSUE THREAD

**Issue by stefan1407993** [microsoft/appcenter#1783] opened 2020-04-03 13:48 UTC
**Describe the solution you'd like**
Just to include an option to notify through webhook when tets is completed.

**Describe alternatives you've considered**
Alternative is integrating Zapier to respond on all emails that arrive from Appcenter that include test in subject.
**Additional context**
It's not useful not to have webook feature for test completion if you have an entire testing environment.

**Comment by winnie** [comment] 2020-05-06 13:59
Thanks for the feature request! We don't have any immediate plans to add this but we'll consider it for our future roadmap.

**Comment by Oddj0b** [comment] 2020-05-11 14:56
Duplicate of #318

**Closed by Oddj0b** 2020-05-11 14:56 UTC
Labels: feature request, test

**Comment by corneliu-serediuc** [comment] 2020-07-01 20:09
I would also be very interested in this feature. Thank you!
