### ISSUE TITLE
Build configuration can't find iOS project

### ISSUE THREAD

**Issue by fabiowingman** [microsoft/appcenter#1241] opened 2019-10-21 14:34 UTC
Not sure why #1107 has been closed as the issue is still there.
I have the exact same issue and have not received any support from the App Center support team.

This is the **toolset_project** response:

`{
    "message": "internal error",
    "err_message": "[Breaker: api-service-build-prod-east-us-build.prod.avalanch.es] Request Timed out",
    "err_stack": "Error: Request Timed out\n    at Timeout.setTimeout [as _onTimeout] (/home/node/data/node_modules/brakes/lib/Circuit.js:111:16)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at unrefdHandle (timers.js:520:7)\n    at Timer.processTimers (timers.js:222:12)"
}`

**Comment by fabiowingman** [comment] 2019-10-22 08:02
For those in the same situation, I found a workaround:
- Remove all the sub-projects and leave only the main build project;
- The config will work now as there is only one project;
- Push all the sub-projects again;
- If you need to make changes to the config, repeat the same process.

**Comment by Oddj0b** [comment] 2019-10-22 08:29
Hi @fabiowingman, I've added my colleague to the ticket but expect a little response time because of time zones.

**Comment by nrajpurkar** [comment] 2019-10-22 17:15
Hi @fabiowingman can you reach out to App Center support for this? We'll be able to to dig into this better via that channel. Thanks!

**Comment by fabiowingman** [comment] 2019-10-23 08:59
Hi @nrajpurkar, I already did that. For now I can use the workaround, so no problem for me.
But I still think you should look into this.

**Comment by stephan-markovic** [comment] 2022-07-01 05:49
Duplicate of: https://github.com/microsoft/appcenter/issues/1107

**Closed by stephan-markovic** 2022-07-01 05:49 UTC
Labels: bug, build, reviewed-DRI
