### ISSUE TITLE
iOS Build Always fails

### ISSUE THREAD

**Issue by Faisal-Manzer** [microsoft/appcenter#174] opened 2019-03-13 07:11 UTC
**What App Center service does this affect?**
React Native SDK, and Build.

**Describe the bug**
Locally Xcode is building normally but is failing on appcenter.

**Expected behavior**
Build successful.

**Additional context**
** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Users/vsts/Library/Developer/Xcode/DerivedData/FinFO-fsqyecelonplshafcobztdahtvlt/Build/Intermediates.noindex/ArchiveIntermediates/FinFO/IntermediateBuildFilesPath/FinFO.build/Release-iphoneos/FinFO.build/Objects-normal/arm64/AppDelegate.o FinFO/AppDelegate.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65
##[section]Finishing: Xcode build (signed)
##[section]Starting: Xcode build (signed)

**Comment by lumaxis** [comment] 2019-03-13 14:38
@Faisal-Manzer Did you figure this issue out yourself?

**Comment by Faisal-Manzer** [comment] 2019-03-13 14:59
Yes, actually it was an error with code push integration.

**Comment by Faisal-Manzer** [comment] 2019-03-16 16:13
Hey, I am reopening this because problem prevails.

iOS Builds are Always failing.
The app was working properly on Local.
I added Archive to App Store also, without any problem it is building.
But on MSAC it is facing an issue.
I tried both signed and unsigned builds, no build succeeds.

![Screenshot 2019-03-16 at 9 34 07 PM](https://user-images.githubusercontent.com/18066439/54478000-7a115900-4833-11e9-8d59-e9596395f62c.png)

---------------------
ld: library not found for -lRCTSettings
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **


The following build commands failed:
	Ld /Users/vsts/Library/Developer/Xcode/DerivedData/FinFO-dsmsfgaczemucsfpiuvbuekjbbmd/Build/Intermediates.noindex/ArchiveIntermediates/FinFO/IntermediateBuildFilesPath/FinFO.build/Release-iphoneos/FinFO.build/Objects-normal/armv7/FinFO normal armv7
	Ld /Users/vsts/Library/Developer/Xcode/DerivedData/FinFO-dsmsfgaczemucsfpiuvbuekjbbmd/Build/Intermediates.noindex/ArchiveIntermediates/FinFO/IntermediateBuildFilesPath/FinFO.build/Release-iphoneos/FinFO.build/Objects-normal/arm64/FinFO normal arm64
(2 failures)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65
##[section]Finishing: Xcode build (signed)
##[section]Starting: Xcode build (signed)

**Comment by gpetrosyan** [comment] 2019-03-18 17:32
The same problem, when we try to build our ios project.

**Comment by Faisal-Manzer** [comment] 2019-03-24 20:23
@patniko @lumaxis help, please.

**Comment by evillemez** [comment] 2019-03-27 21:25
I don't know if this is the same problem or not, but it sounds the same.  iOS (React Native) builds for us have also started failing.  We haven't made changes to our branch configuration, and have been trying to build the same commit that previously worked just a couple of days ago.  Android builds are working as expected... not really sure where to go with it.

```
The following build commands failed:
	PrecompileSwiftBridgingHeader normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65
##[section]Finishing: Xcode build (signed)
##[section]Starting: Xcode build (signed)
==============================================================================
Task         : Xcode
Description  : Build, test, or archive an Xcode workspace on macOS. Optionally package an app.
Version      : 4.130.0
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613730)
==============================================================================
##[section]Finishing: Xcode build (signed)
##[section]Starting: Install Apple provisioning profile
```

@Faisal-Manzer @gpetrosyan Are you still stuck on this too, or did you find something you could fix on your end?

**Comment by evillemez** [comment] 2019-03-27 22:59
I should add, our developers were able to build the same branch locally as well.

@patniko Any thoughts on what we should try if they can build locally but it's stopped working in App Center?

**Comment by DennisPan** [comment] 2019-03-27 23:29
@evillemez @Faisal-Manzer @gpetrosyan Do you mind going to App Center portal and use the Intercom bubble at bottom right to start a conversation with support? That will allow us to collect additional information as needed, which could be hard to do here. Also, looking at the pasted logs here, the failure are different, so they likely need to be resolved separately.

**Comment by evillemez** [comment] 2019-03-28 20:55
Our problem ended up being the version of Cocoapods App Center was using, which must have been updated internally.  We were able to provide a build script to uninstall Cocoapods, and install the version we need, and that got our iOS builds working again.

**Comment by CSharped** [comment] 2019-04-24 17:28
@evillemez , how did you identify that its a different version ? and how did you fix it?

**Comment by vpulec** [comment] 2019-04-26 02:09
I ran into a similar problem and I fixed it by updating CocoaPods and dependencies (the second part was probably not needed to solve this problem)

- sudo gem install cocoapods
- pod update

After that, I have checked-in the Podfile.lock, which updated by CocoaPods version to 1.6.1.

**Comment by puju96** [comment] 2019-05-08 10:16
I am also facing same issue . Native IOS(swift) builds of us are also started failing.previously it was working fine but after new commit it got failed. Locally i am able to build using xcode but in appcenter we are facing problem. Don't know how to solve this issue.

** ARCHIVE FAILED **

The following build commands failed:
	SwiftCodeGeneration normal armv7
	Ld /Users/vsts/Library/Developer/Xcode/DerivedData/Salesgenie_Phase_1-eemuwyhecewcnygojxxsdtijuclm/Build/Intermediates.noindex/ArchiveIntermediates/Salesgenie\ Beta\ Internal\ Prod/IntermediateBuildFilesPath/Salesgenie\ Phase\ 1.build/Adhoc-Prod-iphoneos/Salesgenie\ Phase\ 1.build/Objects-normal/arm64/Salesgenie\ β\	 normal arm64
(2 failures)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65
##[section]Finishing: Xcode build (signed)
##[section]Starting: Xcode build (signed)

**Comment by puju96** [comment] 2019-05-08 11:28
I am also facing same issue . Native IOS(swift) builds of us are also started failing.previously it was working fine but after new commit it got failed. Locally i am able to build using xcode but in appcenter we are facing problem. Don't know how to solve this issue.

** ARCHIVE FAILED **

The following build commands failed:
SwiftCodeGeneration normal armv7Ld /Users/vsts/Library/Developer/Xcode/DerivedData/ProjectName-eemuwyhecewcnygojxxsdtijuclm/Build/Intermediates.noindex/ArchiveIntermediates/ProjectName/IntermediateBuildFilesPath/ProjectName.build/Adhoc-Prod-iphoneos/ProjectName.build/Objects-normal/arm64/ProjectName\	 normal arm64
(2 failures)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65
##[section]Finishing: Xcode build (signed)
##[section]Starting: Xcode build (signed)

**Comment by DennisPan** [comment] 2019-05-08 22:56
@puju96 From a quick glance, the error you are running into is different from the other few reported in the Issue. It usually requires deeper investigation into each case. If you don’t mind, please reach out to our support via the Intercom bubble at bottom right of the portal. That will allow us to collect more details.

**Comment by DennisPan** [comment] 2019-05-08 22:58
Closing this because what I have seen is that this Issue becomes a place where different cases of build failures are reported. For any new build failure, I’d suggest either reach out to support, or creat a new Issue that’s more specifically targeted.

**Closed by DennisPan** 2019-05-08 22:58 UTC
Labels: bug

**Comment by schwamic** [comment] 2019-05-13 08:12
That helped me: https://intercom.help/appcenter/build/ios/my-ios-builds-fail-with-clang-error-linker-command-failed-with-exit-code-1

**Comment by ZenModeRy** [comment] 2019-06-03 15:13
> @CSharped, I ran into a similar problem and I fixed it by updating CocoaPods and dependencies (the second part was probably not needed to solve this problem)
> 
> * sudo gem install cocoapods
> * pod update
> 
> After that, I have checked-in the Podfile.lock, which updated by CocoaPods version to 1.6.1.
> 
> One more note, there is a page that lists the current versions of the libraries used by the MSAC agents: https://docs.microsoft.com/en-us/appcenter/build/software

Question: Did you update cocoapods locally, or with a custom build script?

**Comment by nartc** [comment] 2020-02-04 17:11
@Faisal-Manzer I have just ran into the same problem (but for `-lDoubleConversion`) instead. Have you found a fix for this issue? My local `pod` is 1.8.4 and it is the same as AppCenter's `pod` version. XCode builds successfully locally.
![image](https://user-images.githubusercontent.com/25516557/73768631-f7d99e00-473e-11ea-8e96-b35cbda51e27.png)

**Comment by louzada01** [comment] 2020-02-05 21:17
> @Faisal-Manzer I have just ran into the same problem (but for `-lDoubleConversion`) instead. Have you found a fix for this issue? My local `pod` is 1.8.4 and it is the same as AppCenter's `pod` version. XCode builds successfully locally.
> ![image](https://user-images.githubusercontent.com/25516557/73768631-f7d99e00-473e-11ea-8e96-b35cbda51e27.png)

I'm have a equal problem.

**Comment by Faisal-Manzer** [comment] 2020-02-05 22:12
I don't remember how I solved that. It has been a long time.

**Comment by harshbshah2d** [comment] 2020-04-06 19:18
Same problem with me 
```
** ARCHIVE FAILED **


The following build commands failed:
	Ld /Users/runner/Library/Developer/Xcode/DerivedData/CONNECT2DTELEDENTAL-ermrhfotmwvxkccjppkrjravmuvl/Build/Intermediates.noindex/ArchiveIntermediates/CONNECT2DTELEDENTAL/InstallationBuildProductsLocation/Applications/CONNECT2D\ TELEDENTAL.app/CONNECT2D\ TELEDENTAL normal arm64
(1 failure)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65
```

**Comment by avinashlng1080** [comment] 2020-04-09 03:59
Hello Guys,
Has anyone managed to fix it ?

**Comment by danibots** [comment] 2020-05-22 10:07
In Appcenter Build from Swift/Xcode, I had a similar issue (archive failing, error code 65) but mine looked like it was failing to access files in a particular directory.

`error: /Users/runner/runners/2.168.2/work/1/s/Pods/Target Support Files/...
`
I made two changes and the build succeeded afterward, and I think the success was related to the second change but for completeness I am listing both.
(1) Duplicate the shared schema for the workspace to create a project level version of the scheme that is also marked as shared
(2) Add Pods to source control and push those files to the Github repository I use for the appcenter build. (Before, I excluded pods from source control because they were not part of the workspace, so I believe the error was caused by appcenter looking for files that didn't exist in github)

**Comment by Faisal-Manzer** [comment] 2020-05-22 11:43
Can you all verify the POD version and XCode versions are the same? (on local machine and app center)

**Comment by tusharmutreja200** [comment] 2020-06-19 14:06
+1 ,I am also facing the same issue

**Comment by tusharmutreja200** [comment] 2020-06-19 14:27
Hey guys, I found the solution.
1. Don"t commit  node_modules, Pods, PodFile.lock,package.json on git.
2. Again try to build it on Appcenter, It works

**Comment by affantechcarrot** [comment] 2020-08-19 10:28
@Faisal-Manzer How did you resolve this issue ?

AppDelegate.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler

My Appcenter build getting failed

**Comment by katye333** [comment] 2020-08-29 01:54
Mine is also failing too with the same problem.

**Comment by maxckelly** [comment] 2020-09-08 04:46
I'm also getting the same issue 
```
** ARCHIVE FAILED **


The following build commands failed:
	Ld /Users/runner/Library/Developer/Xcode/DerivedData/aLifeLived-hjrawomvzxvvvdeuplegfjyupvhr/Build/Intermediates.noindex/ArchiveIntermediates/aLifeLived/IntermediateBuildFilesPath/aLifeLived.build/Release-iphoneos/aLifeLived.build/Objects-normal/armv7/A\ Life\ Lived normal armv7
	Ld /Users/runner/Library/Developer/Xcode/DerivedData/aLifeLived-hjrawomvzxvvvdeuplegfjyupvhr/Build/Intermediates.noindex/ArchiveIntermediates/aLifeLived/IntermediateBuildFilesPath/aLifeLived.build/Release-iphoneos/aLifeLived.build/Objects-normal/arm64/A\ Life\ Lived normal arm64
(2 failures)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65
```

**Comment by mdiaz00147** [comment] 2020-09-24 21:31
Working with cordova Im having the same issue, when i run cordova build ios

```
** BUILD FAILED **


The following build commands failed:
        Ld /Users/mdiaz00147/Library/Developer/Xcode/DerivedData/Casey_Research-dtrhdvfxohusmcdsdwqwdixdxhpr/Build/Intermediates.noindex/Casey\ Research.build/Release-iphonesimulator/Casey\ Research.build/Objects-normal/arm64/Binary/Casey\ Research normal arm64
(1 failure)
xcodebuild: Command failed with exit code 65

```

Solution: Open the platform/ios folder with xcode and build it from there and i get it to work

**Comment by fuchien** [comment] 2020-10-13 23:09
I'm also getting the same issue with react-native

`** ARCHIVE FAILED **


The following build commands failed:
	CompileC /Users/runner/Library/Developer/Xcode/DerivedData/ProjectName-fhltpqdzcpwnuyhiscptxpuntjmk/Build/Intermediates.noindex/ArchiveIntermediates/employeeApp-staging/IntermediateBuildFilesPath/Pods.build/Staging-iphoneos/Yoga.build/Objects-normal/armv7/event.o /Users/runner/work/1/s/node_modules/react-native/ReactCommon/yoga/yoga/event/event.cpp normal armv7 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65`

**Comment by yurkins** [comment] 2020-11-10 07:53
For iOS simulator add this to params **-arch x86_64**

**Comment by designervoid** [comment] 2020-11-11 22:01
had `.detoxrc.json` like this:
```
"ios.sim.debug": {
      "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/Project.app",
      "build": "xcodebuild -project ios/Project.xcodeproj -scheme Project -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build",
      "type": "ios.simulator",
      "name": "iPhone 11" 
    },
```
make it to: 
```
"ios.sim.debug": {
      "binaryPath": "ios/build/Build/Products/Debug-iphonesimulator/Project.app",
      "build": "xcodebuild -workspace ios/Project.xcworkspace -scheme Project -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build -arch x86_64",
      "type": "ios.simulator",
      "name": "iPhone 11" 
    },
```
then run:
```
detox build -c ios.sim.debug
```
this gives me bundle. then we can test:
```
detox test -c ios.sim.debug 
```

**Comment by mgithubmessier** [comment] 2022-01-12 16:27
I got this working on my m1 mac by setting up a rosetta terminal to run my react-native run-ios command
https://www.courier.com/blog/tips-and-tricks-to-setup-your-apple-m1-for-development/

**Comment by joomoodle** [comment] 2022-08-20 03:07
I can't generate the build in app center I have this erro



==============================================================================
[command]/usr/local/lib/ruby/gems/2.7.0/bin/pod --version
1.11.3
[command]/usr/local/lib/ruby/gems/2.7.0/bin/pod install --repo-update

[!] Invalid `Podfile` file: cannot load such file -- /Users/runner/work/1/s/node_modules/react-native/scripts/react_native_pods.

 #  from /Users/runner/work/1/s/ios/Podfile:1
 #  -------------------------------------------
 >  require_relative '../node_modules/react-native/scripts/react_native_pods'
 #  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
 #  -------------------------------------------
##[error]The process '/usr/local/lib/ruby/gems/2.7.0/bin/pod' failed with exit code 1
##[error]The 'pod' command failed with error: The process '/usr/local/lib/ruby/gems/2.7.0/bin/pod' failed with exit code 1
##[section]Finishing: Pod install
##[section]Starting: Xcode build (not signed)
