### ISSUE TITLE
Ability to manually upload iOS crash reports

### ISSUE THREAD

**Issue by Bobrovsky** [microsoft/appcenter#289] opened 2019-04-05 06:13 UTC
Somethimes the app crashes during startup / resume or because it become unresponsive. After the app is re-launched, no crash report is uploaded to appcenter. At the same time, the crash is stored locally and [can be retrieved](https://www.macobserver.com/tips/quick-tip/how-to-find-app-crash-reports-iphone-ipad/) 

I would like to have the ability to upload such crashes to appcenter manually. This feature exists in Hockeyapp and is very useful. 

<img width="512" alt="Screenshot 2019-04-05 at 12 12 38" src="https://user-images.githubusercontent.com/8809114/55606838-3065bf80-579c-11e9-9631-39fcd2e861e2.png">

An alternative would be to process such crash reports locally, but that would require us to maintain two crash databases.

**Comment by lumaxis** [comment] 2019-04-05 09:44
Possible duplicate of #31

**Comment by nathanhillyer** [comment] 2019-10-14 21:10
@patniko @winnieli1 @lumaxis is this feature going to be added? We use it frequently– customers will send us crashes from their device that weren't caught by hockey due to the SDK not being initialized yet.

**Comment by winnieli1** [comment] 2019-10-14 21:20
Hi @nathanhillyer - yep, we're just working on documentation right now. It should be done today or tomorrow. Thanks!

**Comment by nathanhillyer** [comment] 2019-10-14 21:33
Excellent, thank you!

**Comment by samardzija** [comment] 2019-10-16 08:37
@winnieli1 will you add support to upload crashes programmatically, from code, into hockey SDK?
We could save exceptions in previous version of Hockey SDK, with ExceptionHandler.saveException(exception, Thread.currentThread(), null);, but it seems there is no support in new Hockey SDK.

**Comment by ronnyremesnik** [comment] 2019-10-30 12:05
Hi @winnieli1, Any updates on that?
Will we be able to upload crashes programmatically, like in hockeyapp 
`ExceptionHandler.saveException` method?

**Comment by Fab1n** [comment] 2019-11-04 11:06
Any update on this one?

**Comment by winnieli1** [comment] 2019-11-04 18:35
Apologies for the delay. We releases this API for uploading Apple logs: https://openapi.appcenter.ms/#/crash/textError_upload

And our ingestion endpoint which accepts a different format: https://docs.microsoft.com/en-us/appcenter/diagnostics/features#upload-reports-to-app-center

Thanks!

**Comment by Bobrovsky** [comment] 2019-11-05 07:02
@winnieli1  Thanks for the link to the documentation, but I would like to ask you to reopen the request.

* I was asking about some UI in the app center, similar to what is implemented in the Hockeapp. Please check the screenshot in the request.

* I tried to upload the crash using the try feature in the API doc, and received HTTP 200. But the crash didn't show up in the list of crashes of my app. What is the ETA for crash to appear in the list of crashes?

**Comment by Fab1n** [comment] 2019-11-05 09:12
We really need a way to manually upload text crash files. We're still doing this via HockeyApp and because in a few days it will be shut off we are left in the dark with this one.

What's the simplest way to achieve the manual upload of crash logs via AppCenter currently (maybe with the new API)?
Can someone help out with a guide on how to do this the simplest way possible?

Requirements:
- Ability to upload a crash text file to a specific app
- Ability to find the uploaded crash on appcenter.ms

I have no problem in doing this via commandline or any other way, but it must be simple and reliable.

Thanks for your help.

**Comment by rbevans-ugh** [comment] 2019-12-16 21:39
Agreed that without a UI to upload logs is really problematic.

**Comment by winnie** [comment] 2020-01-30 01:58
Hey we recently completed this feature! You can now manually [upload Apple crash logs via the UI](https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes-ui) as shown below:

![image](https://user-images.githubusercontent.com/8868628/73413449-b62d9b00-42d9-11ea-99de-737f21fccf61.png)

You can also use our API by following the instructions [here](https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-crashes). 

Thanks!

**Closed by winnie** 2020-01-30 01:58 UTC
Labels: diagnostics, feature request, hockeyapp

**Comment by fernandotcl** [comment] 2020-01-30 10:09
@winnie thanks, but I think the feature is missing a crucial point: when I upload a crash report, I need a link to it (even if it's not yet symbolicated, I'll keep refreshing until it is). Otherwise, I don't know where the crash report went! It will show up in the list of crashes eventually, I'm sure, but I'll have to go find it among potentially thousands of other reports...

**Comment by Fab1n** [comment] 2020-01-30 10:40
> @winnie thanks, but I think the feature is missing a crucial point: when I upload a crash report, I need a link to it (even if it's not yet symbolicated, I'll keep refreshing until it is). Otherwise, I don't know where the crash report went! It will show up in the list of crashes eventually, I'm sure, but I'll have to go find it among potentially thousands of other reports...

Absolutely true! This is super essential, otherwise this feature does not really make sense.

**Comment by gestrich** [comment] 2020-01-30 16:55
One inconsistency between using the web UI and AppCenter's embedded iOS SDK. The web UI uploaded reports will list their release as <app build> (<app version>). But using the AppCenter embedded iOS library, reports will show up in the UI as <app version> (<app build>). This causes duplicate release to show in AppCenter with reversed builds/versions.

**Comment by gestrich** [comment] 2020-01-30 17:04
To add to @fernandotcl 's point - The ability to add the username to the crash report for tracing it would be very helpful. It appears the upload API the browser is using is the same one the swagger documentation was recently removed for: 

https://appcenter.ms/api/v0.1/apps/<owner>/<name>/errors/upload

That has a post parameter for the user name -- error_user_id --. So seems the form in the web browser should be able to accept that input and include with the post request.

**Comment by gestrich** [comment] 2020-02-26 14:23
It appears the web UI to upload reports is not working currently - reports say they were uploaded successfully but they do not ever show in the UI. 

Also, using the API to upload reports I mentioned in the last comment (that uses same underlying API as web I believe) is also failing. 

This issue seems to start 18 hours ago.

`▿ ContentContainer<Response>
  ▿ container : HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
access-control-allow-credentials: false
Strict-Transport-Security: max-age=15724800; includeSubDomains
access-control-max-age: 0
access-control-allow-methods: POST
x-powered-by: Express
Date: Wed, 26 Feb 2020 14:16:15 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 56
Server: nginx/1.15.8
access-control-allow-headers: 
{"code":400,"message":"Unable to send log to ingestion"}`

**Comment by winnie** [comment] 2020-02-26 14:36
Hey apologies for the delay! 

@Fab1n @fernandotcl - great point! I will work with the team to get a feature on our backlog. 

Hey @gestrich - I'm following with the team re: the inconsistency of build / version and the user ID parameter. Can you start a support thread (blue chat bubble on the bottom right) re: crashes not showing up in the UI? I'm not aware of any issues at the moment and our team would like to investigate. Thanks!

**Comment by gestrich** [comment] 2020-02-26 16:15
Hi - I submitted via the form you mentioned too. Hopefully will hear back soon. Thanks.

**Comment by WiesnerPeti** [comment] 2020-05-14 16:11
> To add to @fernandotcl 's point - The ability to add the username to the crash report for tracing it would be very helpful. It appears the upload API the browser is using is the same one the swagger documentation was recently removed for:
> 
> https://appcenter.ms/api/v0.1/apps/owner/appname/errors/upload
> 
> That has a post parameter for the user name -- error_user_id --. So seems the form in the web browser should be able to accept that input and include with the post request.

@gestrich Can you explain where do you send the _error_user_id_ parameter with the https://appcenter.ms/api/v0.1/apps/owner/appname/errors/upload API? As a query like "...errors/upload/error_user_id=userid_url_encoded", or as header like X-Error-User-Id, or as part of the multipart form body data separated with boundary mark? Is this parameter still supported at all?
