### ISSUE TITLE
Add option to select the project within a solution

### ISSUE THREAD

**Issue by potudopotudo** [microsoft/appcenter#1717] opened 2020-03-02 17:08 UTC
Currently I have a UWP I want to build from a Branch. Unfortunately in the same solution I have several Xamarin apps, and WPF projects. When I try to build a branch, it fails because it says it cannot find the SDK for some of the WPF projects that I'm building with .net core. 
` C:\Program Files\dotnet\sdk\2.2.110\Sdks\Microsoft.NET.Sdk.WindowsDesktop\Sdk not found. Check that a recent enough .NET Core SDK is installed and/or increase the version specified in global.json.`

However I just want the UWP project to be built, I don't care about the rest, It would be handy to allow me to select which project to I want to build from a dropdown, otherwise this is unusable as it fails every time I try to build the branch.

**Comment by King-of-Spades** [comment] 2020-03-02 22:20
Thanks for the suggestion! It looks like this is a duplicate of #296. I recommend voting thumbs up for that one, as it has more visibility.

**Closed by King-of-Spades** 2020-03-02 22:20 UTC
Labels: build, duplicate, feature request

**Comment by potudopotudo** [comment] 2020-03-03 08:33
Sure, that's exactly what I wanted! thanks!
