### ISSUE TITLE
Xamarin Forms - line numbers in stack traces

### ISSUE THREAD

**Issue by Mikilll94** [microsoft/appcenter#1848] opened 2020-05-08 18:51 UTC
**Describe the solution you'd like**
Currently, there is a problem with Xamarin.Forms apps, because if you compile Android or iOS app in release mode, crash reports do not contain line numbers.

I don't know if line numbers in the crash reports are not supported via App Center or I am doing something wrong.

**Comment by DmitriyKirakosyan** [comment] 2020-12-22 15:45
Hi @Mikilll94 ,

I'm sorry for the late replay and thank you for getting in touch with us!

Closing this issue as a duplicate of https://github.com/microsoft/appcenter/issues/165.

Please follow the original issue.
Thanks.

**Closed by DmitriyKirakosyan** 2020-12-22 15:45 UTC
Labels: feature request

**Comment by rhult** [comment] 2023-09-28 15:08
(Copying this from the dup) I got tired of waiting for this to never happen so I put together a small tool that helps somewhat. See the repo at https://github.com/rhult/crash-sharpener 

It is not a full solution, but it does two things:

1. Add information to stack traces that can be uploaded as handled errors to App Center
2. A tool you can run locally to symbolicate those stack traces

You can use this to automate symbolicating by downloading the errors from App Center using its API, and then symbolicate them on your machine. I have tested it with iOS and Android on .net7 and it works well. I get line numbers from release builds this way.
