### ISSUE TITLE
Silent push notifications for Android

### ISSUE THREAD

**Issue by wegascee** [microsoft/appcenter#87] opened 2019-02-20 15:47 UTC
**Describe the solution you'd like**
You already support silent push notifications for iOS, but not for Android. I'd like to see that option as well, because it is possible with FCM (data message).

**Describe alternatives you've considered**
Perhaps use Azure or directly FCM instead of AppCenter Push Notifications.

**Additional context**
I don't want to show the notification immediately to the user. First, I want to process the content and afterwards I want to show a local push notification message.

Also I'm not the only who wants this feature. See related [SO thread](https://stackoverflow.com/questions/49155493/how-can-i-send-a-silent-notifications-using-app-center-push-service).

**Comment by jwargo** [comment] 2019-03-08 19:11
@wegascee thanks for suggesting this. We hear this periodically from customers and we want to fix this for you. I've added this feature to the backlog and will try to get started on it soon.

**Comment by jwargo** [comment] 2019-03-26 18:22
@wegascee we're trying to fit this into some updates we're doing for the GCM-FCM migration. Stay tuned.

**Comment by jruiz666** [comment] 2019-06-03 19:09
It is necessary to perform this function again in the application center.

Mechanism for sending and receiving silent notifications in xamarin android and xamarin forms.

**Comment by KSemenenko** [comment] 2019-06-26 21:03
I also need such functionality

**Comment by SogoGolf** [comment] 2019-06-28 02:51
Same, didn't realise till i saw this that AppCenter didn't support silent push on Android, which is a problem for us. Definitely needed, thanks

**Comment by ayngling** [comment] 2019-07-05 10:54
I'll echo the last poster. This is really needed.

**Comment by tharindup** [comment] 2019-07-05 11:00
**This is a must needed feature** since GCM is also deprecated. Cannot handle background notifications with the FirebaseMessagingService.

**Comment by mnidhk** [comment] 2019-09-10 13:16
News on this matter?

**Comment by jwargo** [comment] 2019-09-10 14:02
@mnidhk We're still working on it. We've recently started a monthly release schedule for the SDK and we're working on our feature roadmap for the next quarter.

**Comment by jwargo** [comment] 2019-09-26 12:40
@edupxavier I apologize for this, but yeah, background notifications on Android is problematic right now. You can do it in Azure Notification Hubs, but we have some work to do to support it on App Center Push. We're working on getting that in there.

**Comment by geekazoid-at** [comment] 2019-10-03 10:03
Same here. We really need it and I guess I will have to switch to another platform :(

**Comment by ayngling** [comment] 2019-10-09 13:47
I'll echo the previous poster. I really need this, and I'd be surprised if the same was not true for many others.

**Comment by RioFiveJack** [comment] 2019-11-05 09:29
i also need this now for my notification

**Comment by edupxavier** [comment] 2019-11-05 09:51
@geekazoid-at did you switched or still waiting like me?

**Comment by RioFiveJack** [comment] 2019-11-05 10:40
@edupxavier actually you could send push notification to background, but the problem is appcenter Push can't handle the message when the apps is closed, i need other 3rd party Library to handle this, and currently this is quite annoying things to do that.

**Comment by geekazoid-at** [comment] 2019-11-05 11:32
> @geekazoid-at did you switched or still waiting like me?
@edupxavier: We switched to rnfirebase. Migration was easy and I am 100% satisfied with the pure firebase solution. I had rnfirebase experience before, but in general it is quite well documented and not to hard to implement.

I'll stick to rnfirebase for now. Imho, not having silent pushes makes appcenter pushes completely obsolete but I am still very happy for having appcenter with all it's other features.

**Comment by edupxavier** [comment] 2019-11-05 11:59
> Imho, not having silent pushes makes appcenter pushes completely obsolete but I am still very happy for having appcenter with all it's other features.

@geekazoid-at , I agree but now I am afraid of trying new features for latter knowing that it's partially implemented.

No more of "do xyz with just two lines of code". :)

**Comment by RioFiveJack** [comment] 2019-11-05 12:12
@jwargo while you're at this , could you also implement support on Local Notification, currently my problem is i want to receive silent notification, but in some cases, when it's important i will need send to local notification, It will be twice the works if we handled the local notification on notification received and also App Center Push on notification receive when the user clicked the notification

**Comment by jwargo** [comment] 2019-11-05 16:31
@RioFiveJack can you tell me more about this need?  I have heard a couple of others ask for support for local notifications, but that's a client-side SDK feather that's already on the device. What's different about doing it through App Center Push? What's the value add App Center provides here that you can't already have today?  How would this work differently if App Center did it for you?  I'm really trying to understand the use case here and I really don't get it.

**Comment by RioFiveJack** [comment] 2019-11-06 03:47
@jwargo I want to display notification when user is in our app and there's some message from other user, I could achive this using Local Notification, but doing this from 3rd party library, will make my app have 2 listener :  Push.setListener({onPushNotificationReceived : {}})  and 3rd party listener for local push notification.
Since right now Push notification listener can't accept any notification from Local Notification, and usually any Push notification library already have what FCM / GCM modules and I don't need it anymore so I would like to keep our app size small by reducing the number of library we need to use.

**Comment by jwargo** [comment] 2020-02-04 15:21
Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.

**Closed by jwargo** 2020-02-04 15:21 UTC
Labels: feature request, push

**Comment by nbsoftware** [comment] 2020-02-04 15:25
Ouch...

**Comment by jwargo** [comment] 2020-02-04 15:29
@nbsoftware so sorry.

**Comment by shnaz** [comment] 2020-02-04 15:34
@jwargo Sad news. Do you know if Azure Notification Hubs will support Xamarin.Forms?

**Comment by jwargo** [comment] 2020-02-04 15:48
@shnaz https://docs.microsoft.com/en-us/dotnet/api/overview/azure/notification-hubs?view=azure-dotnet

**Comment by DamienDoumer** [comment] 2020-02-04 23:41
Ooh... sadly... 😥😥😥 The idea was great, the level of abstraction above those services was awesome... though not fully matured...
