### ISSUE TITLE
iOS and Android Build Fail when Test on Real Device is Toggled on

### ISSUE THREAD

**Issue by ArronJLinton** [microsoft/appcenter#1878] opened 2020-05-31 02:52 UTC
**What App Center service does this affect?**
React Native SDK, and Build.

**Describe the bug**
Locally Xcode is building normally, but it fails in appcenter with Test on Real Device Toggled on. When it's toggled off, the build is successful.

**Expected behavior**
Build successful.

Additional context
##[error]Error: /usr/local/bin/appcenter failed with return code: 3
##[section]Finishing: Run generated tests on real devices

**Comment by MohammedFadin** [comment] 2021-12-13 20:54
Hello,

is there a fix for this issue? We are facing a similar challenge as described above. The issue is only triggered when the “Test on real devices” is on. Returning error code 1. Without providing much information on what went wrong

**Comment by benmagos** [comment] 2022-03-07 22:51
We are experiencing this same issue!

It appears that `any_top_1_device` is not set to any default device. This is my Android build log but it also crashes on iOS for our React Native application.

```logFilter, request: {
2022-03-03T16:48:01.8220980Z   "rawResponse": false,
2022-03-03T16:48:01.8221520Z   "queryString": {},
2022-03-03T16:48:01.8224050Z   "url": "https://api.appcenter.ms/v0.1/apps/Tiled/Andriod-Tiled/test_runs/a74653d3-ae17-4861-84d5-f853c68e8e1a/start",
2022-03-03T16:48:01.8224750Z   "method": "POST",
2022-03-03T16:48:01.8225140Z   "headers": {
2022-03-03T16:48:01.8226010Z     "Content-Type": "application/json; charset=utf-8",
2022-03-03T16:48:01.8227100Z     "***-agent": "appcenterCli/2.10.8 NodeJS/v10.15.3 darwin/19.6.0",
2022-03-03T16:48:01.8228540Z     "x-api-token": ***
2022-03-03T16:48:01.8229460Z   },
2022-03-03T16:48:01.8231630Z   "body": "{\"test_framework\":\"ui_test\",\"device_selection\":\"any_top_1_device\",\"locale\":\"en_US\",\"test_series\":\"launch-tests\",\"test_parameters\":{\"tests\":{\"method\":{\"AppCenter.UITest.Android.dll\":[\"AppCenter.UITest.Android.Tests.AppDoesLaunch\"]},\"fixture\":{\"AppCenter.UITest.Android.dll\":[\"AppCenter.UITest.Android.Tests\"]}},\"excluded_tests\":{\"method\":{\"AppCenter.UITest.Android.dll\":[]},\"fixture\":{\"AppCenter.UITest.Android.dll\":[]}},\"msft/test-run-origin\":\"Build/Launch\"}}"
2022-03-03T16:48:01.8233040Z }
2022-03-03T16:48:05.2805370Z Response status code: 400
2022-03-03T16:48:05.2846360Z Body: {"message":"Empty device selection 'any_top_1_device'"}
2022-03-03T16:48:05.2860210Z Starting test run... failed.
2022-03-03T16:48:05.2861900Z Error: Empty device selection 'any_top_1_device'
```

**Comment by benmagos** [comment] 2022-03-07 22:52
This has always been an issue for us in using AppCenter; I am just now taking the time to investigate why these builds were crashing, specifically; and it is solely due to this error.

**Comment by Adnan-Bacic** [comment] 2022-03-18 08:18
for me this seems to only happen with IOS on the production build. other IOS builds work and all Android builds work.

**Comment by Rob97** [comment] 2022-03-23 03:08
Having the same issue as well on my IOS.

**Comment by jerimiah797** [comment] 2023-04-04 17:40
Interesting timing with closing this bug.. any_top_1_device has actually been working for the better part of a year (perhaps even 2 years!) , and only started failing on Android about 5 days ago. 

```
Running test in App Center Test
total 61840
drwxr-xr-x  3 runner  staff        96 Apr  4 17:16 .
drwxr-xr-x  4 runner  staff       128 Apr  4 17:16 ..
-rw-r--r--  1 runner  staff  31661980 Apr  4 17:16 app-internal-release.apk
Test Platform is:
android
/Users/runner/work/1/a/build/app-internal-release.apk
Target environment for tests is: 
Staging
Preparing tests... done.
Validating arguments... done.
Creating new test run... done.
Validating application file... done.
Uploading files... done.
Starting test run... failed.
Error: Empty device selection 'any_top_1_device'

Further error details: For help, please send both the reported error above and the following environment information to us by going to https://appcenter.ms/apps and opening a support ticket (using the help menu in the upper right corner of the screen)


    Environment: darwin
    App Upload Id: geocaching/Adventures-Android
    Timestamp: 1680628656892
    Operation: RunAppiumTestsCommand
    Exit Code: 3
##[error]The process '/bin/bash' failed with exit code 3
##[error]Bash failed with error: The process '/bin/bash' failed with exit code 3
##[section]Finishing: Post Build Script
```

Please re-open this.

**Comment by harounandroid** [comment] 2023-04-04 23:05
facing same issue , Please re open this issue

**Comment by Priskorn** [comment] 2023-04-05 07:36
Thanks for the feedback. I will ask the team to take a look again

**Comment by AnatolyPristensky** [comment] 2023-04-05 10:27
Hello @harounandroid, 
We've confirmed this issue and now working on a fix. Will update this conversation once fix will be done.

**Comment by harounandroid** [comment] 2023-04-05 10:50
Super !

**Comment by Adnan-Bacic** [comment] 2023-04-05 11:43
for what its worth, my android builds started working right as @Priskorn initially said it was fixed, and recently started failing again. so the timeline for me is:

Mar 30 - builds

Apr 3 - builds

Apr 5 - fails

**Comment by nikkorlov** [comment] 2023-04-05 11:50
@Adnan-Bacic @harounandroid @jerimiah797 
Thank you for reaching out to us!
We appreciate you bringing the problem to our attention, and we want to inform you that we are already working on resolving it.
Please stay connected with us, and we will keep you updated on the progress!😄

**Comment by robertmaxted** [comment] 2023-04-12 15:08
Same issue for me too:

Preparing tests... failed.
Error: Failed to prepare UI Test artifacts using command "test-cloud.exe prepare" with error message:
There was an unknown error preparing test artifacts, please try again. If you can't work out how to fix this issue, please contact support.
##[error]Error: The process '/usr/local/bin/appcenter' failed with exit code 3

**Comment by team-caalm** [comment] 2023-04-14 20:01
same issue for me too .. 



Response status code: 400
Body: {"message":"Empty device selection 'any_top_1_device'"}
Starting test run... failed.
Error: Empty device selection 'any_top_1_device'

Further error details: For help, please send both the reported error above and the following environment information to us by going to https://appcenter.ms/apps and opening a support ticket (using the help menu in the upper right corner of the screen)


    Environment: darwin
    App Upload Id: Beta_tester3/first
    Timestamp: 1681502185375
    Operation: RunManifestTestsCommand
    Exit Code: 3
##[error]Error: The process '/usr/local/bin/appcenter' failed with exit code 3

**Comment by team-caalm** [comment] 2023-04-14 20:02
we are faceing same issues any solution ?

**Comment by borisnetweb** [comment] 2023-04-17 18:58
Same issue - tests enabled, Empty device selection 'any_top_1_device'" - never seen this one before, first time experienced today. ETA on when the fix is coming?

**Comment by nikkorlov** [comment] 2023-04-19 06:26
Hello everyone!

I'm pleased to announce that the issue has been resolved, and everything is now functioning properly. I would like to express my gratitude to everyone who contributed to resolving the problem and provided their feedback.

Thank you all for your help and patience as we worked to resolve this issue! 😃

**Closed** 2023-04-19 15:18 UTC
Labels: bug, build, test, reviewed-DRI

**Comment by jerimiah797** [comment] 2023-04-20 22:41
Can confirm, it is working as expected again on Android Test Center. Thanks so much, our CI/CT system is once more functional!

**Comment by Adnan-Bacic** [comment] 2024-03-13 13:41
having problems again with this
