### ISSUE TITLE
Add the ability to intercept or customize push notifications

### ISSUE THREAD

**Issue by Mrnikbobjeff** [microsoft/appcenter#1218] opened 2019-10-17 21:28 UTC
**Describe the solution you'd like**
Ideally, I would like to be able to plug in my own notification intent builder to be able to customize my push messages with sounds, or even decide whether they should fire at all, as the user should be able customize which messages should be visible via an alert. This would also allow me to localize my push messages on my device.

**Describe alternatives you've considered**
It is currently impossible to prevent displaying the push notification. The only alternative would be to sync every user option to my server to decide who gets which push notification under which circumstance. This is not a desirable solution, as something like a x hour mute function should not need to sync with a server to function - also, changes that were made while the user was offline which would be synced on the next app restart do not occur before push notifications are received once the device connects again. So there is no viable alternative.

**Comment by amchew** [comment] 2019-10-18 19:10
Thank you @Mrnikbobjeff for sharing your user scenario and feature request. @jwargo fyi ^

**Comment by jwargo** [comment] 2019-10-18 19:58
@Mrnikbobjeff thanks for this suggestions. We're knee deep in feature planning for next week and some of this aligns somewhat with what we're hearing from other customers. Would you be willing to have a phone conversation to discuss your app's needs?  I specifically want to better understand what you mean preventing display of a notification. My email address is on my GitHub profile, please reach out direct if you can chat.

**Comment by Mrnikbobjeff** [comment] 2019-10-19 23:05
I sent you an email, I would love to talk to you directly about the details of doing this right! Thank you for your offer!

**Comment by jwargo** [comment] 2019-10-28 13:49
related/duplicate of https://github.com/microsoft/appcenter/issues/87

**Comment by jwargo** [comment] 2020-02-04 14:56
Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.

**Closed by jwargo** 2020-02-04 14:56 UTC
Labels: feature request, push
