### ISSUE TITLE
Bring back the email registration/account creation that was part of the HockeyApp

### ISSUE THREAD

**Issue by cogwurx** [microsoft/appcenter#1584] opened 2020-01-16 14:13 UTC
**Describe the solution you'd like**
The return of feature HockeyApp had where an invitee to test was given the option to register with an email like from their mobile device. 

**Describe alternatives you've considered**
After asking AppCenter support about this, we were told this: 

`Hi, thanks for getting in touch! For now, if you want to create the App Center account. you have to use your social or MS account. But there is a workaround, you can still register HockeyApp account and HockeyApp account would be sync to App Center automatically. Note that, HockeyApp account can't be registered directly, so please invite users to your app and then people can register the HA account by the invitation email.` 

Not sure how long this workaround will be in place, but this doesn't sound like a sustainable solution. The better solution is to put back that feature that was part of HockeyApp.

**Additional context**
The current AppCenter solution for when someone receives an invite to test the App involves either a social media account or MS account to register. Prior to Microsoft's acquisition of HockeyApp, when someone received an invite to test an app they clicked the email link and created an account/registered their device with HockeyApp. Rather simple process. Now that we are in AppCenter, the invites our testers receive don't give them an option to register simply with the service, but to either use a Social media account or have an MS account. This is proving quite challenging for non-technical testers that want to test their app we built for them for approval before submitting to the stores. The MS accounts they have with their companies are not being recognized by AppCenter/Azure, so they can't login or they have to attempt logins multiple times in order to be miraculously recognized that they do have an MS account. It is also unreasonable to ask our clients to login with their Facebook accounts given business restrictions on Facebook usage at work and frankly they shouldn't be asked to login with their personal social media for something that is work related.

**Comment by nhpolanco** [comment] 2020-02-27 23:02
Seconded! We've been forced to explore other options that allow email based account creation.

@cogwurx Is your work around still in place? Im unable to find a valid url to the hockey app account creation page.

**Comment by nhpolanco** [comment] 2020-02-27 23:02
Same issue is highlighted in https://github.com/microsoft/appcenter/issues/190 & https://github.com/microsoft/appcenter/issues/1375 - @ScottArbeit Has this made it onto your roadmap?

**Comment by lumaxis** [comment] 2020-03-09 17:23
Closing this as a duplicate of the above mentioned issues.

**Closed by lumaxis** 2020-03-09 17:23 UTC
Labels: account, duplicate, feature request, hockeyapp
