### ISSUE TITLE
Download Numbers are not Present on App Center for Builds Uploaded Through HockeyApp

### ISSUE THREAD

**Issue by stew3725** [microsoft/appcenter#626] opened 2019-06-24 17:09 UTC
**What App Center service does this affect?**
App Center on Web - Distribute Tab - Releases Section

https://appcenter.ms/users/stewart-holder-nliu/apps/Robert-Half/distribute/releases

**Describe the bug**
The download numbers for each release are not present on App Center for builds uploaded through HockeyApp, even though they are present on HockeyApp. 

**To Reproduce**
1. Go to the Hockey App and click on the Versions tab - 'https://rink.hockeyapp.net/manage/apps/789622/app_versions'
2. Look to the right where downloads are present and notice that numbers are present for downloads by each release
3. Navigate to the App Center screen and notice there are no download numbers available by each release

**Expected behavior**
A number of downloads is present by each release 

**Screenshots**
<img width="1433" alt="Screen Shot 2019-06-24 at 10 29 56 AM" src="https://user-images.githubusercontent.com/52169895/60037625-ac72f380-9677-11e9-8a3f-13378607e961.png">

<img width="1418" alt="Screen Shot 2019-06-24 at 10 30 02 AM" src="https://user-images.githubusercontent.com/52169895/60037626-ad0b8a00-9677-11e9-9bc7-17076c0f4edc.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave Version 10.14.5
 - Browser Chrome 
 - Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by kpiteira** [comment] 2019-06-26 11:01
Thank you for the report. This is indeed a data that is not synchronized, but you will see download counts accumulating in App Center in the following conditions:
- Your testers download the release from the App Center page
- Your testers use the Pink HockeyApp Android app (https://play.google.com/store/apps/details?id=com.microsoft.hockeyapp.testerapp&hl=en_US)
- You integrate the App Center SDK with the "Distribute" module in your app as a replacement of the HockeyApp SDK for in-app updates

**Comment by derpixeldan** [comment] 2019-07-17 16:10
Closing as this is by design, we don't synchronize the download numbers. It requires to use App Center infrastructure to count the downloads.

**Closed by derpixeldan** 2019-07-17 16:10 UTC
Labels: bug, hockeyapp
