### ISSUE TITLE
Possibility to sort analytics in App Center on build instead of version

### ISSUE THREAD

**Issue by TrulsHaraldsson** [microsoft/appcenter#2387] opened 2022-02-18 11:23 UTC
Hi, I recently posted this [issue in the AppCenter SDK respository](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1629) but was redirected here instead.

Anyway, when build our application we set, among others, two assembly attributes: Version, and InformationalVersion. Example
```
<Version>13.2.0.0</Version>
<InformationalVersion>13.2 (Development)</InformationalVersion>
```
The firs tag, Version, is actually set dynamically from our pipeline so the build version is incremented on each build. While the second attribute is more of an information version for the user that is displayed in the header or start screen of our application.

Anyway, when we start the application the following data is sent to App Center:
```
"device": {
....
"appVersion": "13.2 (Development)", 	
"carrierCountry": "US", 	
"appBuild": "13.2.123", 
...
}
```
If we then head over to App Center's webpage and go to the analytics tab and select a version, we can only filter events on the "appVersion" and not the "appBuild".
![image](https://user-images.githubusercontent.com/4319850/154646125-876e6780-acf5-4d93-adcd-8a570881416a.png)

I guess there are two outcomes here:
1. I have misunderstood the documentation of what the intention of Version vs InformationalVersion is and I'm not using them correctly and I have to change how we handle it.
2. Or AppCenter webpage could give the option to browse/filter on appBuild.

Information about our app:
- Windows Desktop application
- Running on .NET framework 4.8 (but we're migrating towards .NET 6 at this moment)

**Comment by AnatolyPristensky** [comment] 2022-02-18 11:31
Hello @TrulsHaraldsson,
As I said in previous ticket - you should create a ticket at the AppCenter portal, here is the [link](https://docs.microsoft.com/en-us/appcenter/help#accessing-app-center-free-support) on how to do this.
Closing this one as duplicate of #1629

**Comment by TrulsHaraldsson** [comment] 2022-02-18 11:39
@AnatolyPristensky Sorry for the confusion, I followed the link you gave me which said that I should use the support/question mark button in App Center 
![image](https://user-images.githubusercontent.com/4319850/154675226-5b45e1f5-0fcd-4a91-880f-d0d5a88e0dc5.png)

and in that popup dialog after clicking on that button I saw this link
![image](https://user-images.githubusercontent.com/4319850/154675355-52ce4735-a889-4898-a6fd-0e6fddbf2ca7.png)

which redirects to this place again.
![image](https://user-images.githubusercontent.com/4319850/154675425-e6f7d3f7-1865-463e-a904-ead2d92da11e.png)

Sorry for my confusion. Should I contact the support by email instead?

**Comment by TrulsHaraldsson** [comment] 2022-02-18 13:22
Okey. I was a bit confused there for a while :) 

Here is some information about our application target platform (I'll updated the initial comment with this information): 
- Windows Desktop application
- Running on .NET framework 4.8 (but we're migrating towards .NET 6 at this moment)

**Comment by AnastasiaKubova** [comment] 2022-02-21 11:58
Hi, @TrulsHaraldsson! 
The App Center SDK tries to get an available application version [here](https://github.com/microsoft/appcenter-sdk-dotnet/blob/develop/SDK/AppCenter/Microsoft.AppCenter.WindowsDesktop/Utils/DeviceInformationHelper.cs#L180). We also have a similar [feature request](https://github.com/microsoft/appcenter/issues/1313) about it. Is this feature request suit your issue?

**Comment by TrulsHaraldsson** [comment] 2022-02-21 14:02
@AnastasiaKubova Yes that feature would solve our problems

**Comment by AnastasiaKubova** [comment] 2022-02-22 05:01
Thanks for your response. I'm going to close this issue as a duplicate, let's track the progress of this feature [here](https://github.com/microsoft/appcenter/issues/1313).

**Closed by AnastasiaKubova** 2022-02-22 05:01 UTC
Labels: feature request, analytics, Portal
