### ISSUE TITLE
As of now there is no feature in App center which controls actions like "delete" app. Can you add a feature to add approval process before "delete" action" action is taken for the app. This will save from accidental deletion of app from app center

### ISSUE THREAD

**Issue by gautammanish** [Microsoft/appcenter#341] opened 2019-04-23 21:25 UTC
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by patniko** [comment] 2019-04-23 21:54
Closing this as a dupe of issue #105

**Closed by patniko** 2019-04-23 21:54 UTC
Labels: feature request
