### ISSUE TITLE
nuget libraries are not properly copied over to AppData\Local\assembly

### ISSUE THREAD

**Issue by farzonl** [microsoft/appcenter#2579] opened 2023-08-25 03:32 UTC
**Describe the bug**
```bash
Exception thrown: 'System.ComponentModel.Win32Exception' in SQLitePCLRaw.batteries_v2.dll
Exception thrown: 'System.Exception' in SQLitePCLRaw.batteries_v2.dll
2023-08-24 23:27:29.932 [AppCenter] ERROR: Failed to initialize sqlite3 provider.
System.Exception: Library e_sqlite3 not found
plat: win
suffix: DLL
possibilities (2):
    1) C:\Users\username\AppData\Local\assembly\dl3\GPDLTRHM.2DD\CW8H18OX.ZAX\f0a1aaf0\009d039e_e66ed801\runtimes\win-x64\native\e_sqlite3.dll
    2) C:\Users\username\AppData\Local\assembly\dl3\GPDLTRHM.2DD\CW8H18OX.ZAX\f0a1aaf0\009d039e_e66ed801\e_sqlite3.dll
win TryLoad: C:\Users\username\AppData\Local\assembly\dl3\GPDLTRHM.2DD\CW8H18OX.ZAX\f0a1aaf0\009d039e_e66ed801\runtimes\win-x64\native\e_sqlite3.dll
thrown: System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
```

%AppData%\Local\assembly\dl3\GPDLTRHM.2DD\CW8H18OX.ZAX\f0a1aaf0\009d039e_e66ed801

is missing runtimes directory.

**Describe the solution you'd like**
The runtimes directory from: 
`C:\Users\username\.nuget\packages\sqlitepclraw.lib.e_sqlite3\2.1.0\runtimes`
needs to be copied to 
%AppData%\Local\assembly\dl3\GPDLTRHM.2DD\CW8H18OX.ZAX\f0a1aaf0\009d039e_e66ed801

when I copy over the runtimes directory manually everything works fine.

**Comment by farzonl** [comment] 2023-08-25 04:42
looks like a duplicate of https://github.com/microsoft/appcenter/issues/2527 and https://github.com/microsoft/appcenter-sdk-dotnet/issues/1716

However I'm on 5.0.2 and im using Package References.

**Comment by DmitriyKirakosyan** [comment] 2023-08-28 08:12
Hi @farzonl , thank  you for reaching out!

Have you tried to reference the fixed version of `SQlitePCL.raw` directly in your project? Would it resolve the issue?

**Comment by farzonl** [comment] 2023-08-28 17:04
No upgrading wasn't enough to fix my problem. I had to specify runtime Identifiers. got the idea from this xunit test change: https://github.com/ericsink/SQLitePCL.raw/commit/1b2e50535cf3c3e4811197b72b7dc694715227f6?diff=unified#diff-16e5545b7bb35fe0eae10ea1944bb876be6622be8dcd39ca8b9d3fed18b9c6c6

My work around via csproj: 
```xml
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x86' ">
  <PlatformTarget>x86</PlatformTarget>
  <DebugSymbols>true</DebugSymbols>
  <DebugType>full</DebugType>
  <Optimize>false</Optimize>
  <RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
  <RuntimeIdentifier>win-x86</RuntimeIdentifier>
</PropertyGroup>
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x86' ">
  <PlatformTarget>x86</PlatformTarget>
  <DebugType>pdbonly</DebugType>
  <Optimize>true</Optimize>
  <RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
  <RuntimeIdentifier>win-x86</RuntimeIdentifier>
</PropertyGroup>
 <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
  <PlatformTarget>x64</PlatformTarget>
  <DebugSymbols>true</DebugSymbols>
  <DebugType>full</DebugType>
  <Optimize>false</Optimize>
  <RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
</PropertyGroup>
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
  <PlatformTarget>x64</PlatformTarget>
  <DebugType>pdbonly</DebugType>
  <Optimize>true</Optimize>
  <RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
</PropertyGroup>
```

**Comment by farzonl** [comment] 2023-08-28 17:18
No updating didn't fix anything.

**Comment by DmitriyKirakosyan** [comment] 2023-08-31 17:44
@farzonl, I believe it's a duplicate of https://github.com/microsoft/appcenter-sdk-dotnet/issues/1583/.

Although the issue you referenced was marked as 'resolved', it wasn't actually addressed in the SQLitePCL.raw side; it was simply closed without a fix. Your situation appears distinct since you're encountering the problem even with a PackageReference project.

Please refer to #1583 for all related links.

**Comment by farzonl** [comment] 2023-09-01 03:44
@DmitriyKirakosyan  The call stack I'm seeing and https://github.com/microsoft/appcenter-sdk-dotnet/issues/1583 are distinct so I'm still unsure if it is a dupe. But the good news is I have a fix: https://github.com/ericsink/SQLitePCL.raw/pull/553.  I'll ask the original poster if he would like to try my fix?

The issue has a few parts. First and formost SQLITEPCL.Raw won't copy over `e_sqlite3.dll` from nuget unless you specify an architecture type.  like so:

```xml
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x86' ">
  <PlatformTarget>x86</PlatformTarget>
  <DebugSymbols>true</DebugSymbols>
  <DebugType>full</DebugType>
  <Optimize>false</Optimize>
  <RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
  <RuntimeIdentifier>win-x86</RuntimeIdentifier>
  <OutputPath>bin\x86\Debug\</OutputPath>
</PropertyGroup>
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x86' ">
  <PlatformTarget>x86</PlatformTarget>
  <DebugType>pdbonly</DebugType>
  <Optimize>true</Optimize>
  <RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
  <RuntimeIdentifier>win-x86</RuntimeIdentifier>
  <OutputPath>bin\x86\Release\</OutputPath>
</PropertyGroup>
 <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
  <PlatformTarget>x64</PlatformTarget>
  <DebugSymbols>true</DebugSymbols>
  <DebugType>full</DebugType>
  <Optimize>false</Optimize>
  <RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  <OutputPath>bin\x64\Debug\</OutputPath>
</PropertyGroup>
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
  <PlatformTarget>x64</PlatformTarget>
  <DebugType>pdbonly</DebugType>
  <Optimize>true</Optimize>
  <RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>
  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  <OutputPath>bin\x64\Release\</OutputPath>
</PropertyGroup>
```
That only gets your dll in your Release\Debug directory though. Second Problem is that VSTO copies libraries to temp directories. More on that here: https://web.archive.org/web/20140424032444/http://blogs.msdn.com/b/vsod/archive/2008/11/01/office-customization-creates-loads-dll-from-temporary-folder.aspx

This is where my fix comes in to play. Using `System.Reflection.Assembly.GetExecutingAssembly().CodeBase` we can get the original directory of the library where all the other dependency libraries  like `e_sqlite3.dll` will also be. 


More instruction on how I confirmed the fix and someone else could try:
https://github.com/ericsink/SQLitePCL.raw/issues/552#issuecomment-1702104645

**Comment by DmitriyKirakosyan** [comment] 2023-09-01 12:59
@farzonl, great news! Thanks a lot for your excellent work in finding and fixing the problem. We hope the folks in charge of `SQLitePCL.raw` will soon accept your changes, allowing us to update it in our SDK. Your help is much appreciated!

**Comment by farzonl** [comment] 2023-11-07 18:24
@DmitriyKirakosyan   This issue has been resolved by https://github.com/ericsink/SQLitePCL.raw/pull/553

What is needed to role the appcenter sdk?

**Comment by DmitriyKirakosyan** [comment] 2023-11-08 07:51
We'll roll the new release into our SDK as soon as it's out. 👍

Related thread https://github.com/microsoft/appcenter-sdk-dotnet/issues/1583.

**Comment by DmitriyKirakosyan** [comment] 2023-11-20 07:30
fixed in https://github.com/microsoft/appcenter-sdk-dotnet/pull/1765

**Closed** 2024-06-27 06:56 UTC
Labels: feature request, sdk, sdk-next-release
