### ISSUE TITLE
[Xamarin.UITest][net8] System.Exception : file does not exist: {plistPath}

### ISSUE THREAD

**Issue by jeromelaban** [microsoft/appcenter#2584] opened 2023-09-11 11:39 UTC
Using Xamarin.UITest 4.2.0 with .NET 8 Preview 7, testing with Xcode 14.3.1 in the iOS simulator fails with the error below.

The same tests works properly using .NET 7.0.400.

```
System.Exception : file does not exist: {plistPath}
StackTrace:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
--Exception
   at Xamarin.UITest.iOS.iOSAppLauncher.LaunchAppLocal(IiOSAppConfiguration appConfiguration, HttpClient httpClient, Boolean clearAppData)
   at Xamarin.UITest.iOS.iOSAppLauncher.LaunchApp(IiOSAppConfiguration appConfiguration, HttpClient httpClient, TestCloudiOSAppConfiguration testCloudAppConfiguration, HttpClient testCloudWsClient, HttpClient xtcServicesClient, Boolean testCloudUseDeviceAgent)
   at Xamarin.UITest.iOS.iOSApp..ctor(IiOSAppConfiguration appConfiguration, IExecutor executor)
   at Xamarin.UITest.iOS.iOSApp..ctor(IiOSAppConfiguration appConfiguration)
   at Xamarin.UITest.Configuration.iOSAppConfigurator.StartApp(AppDataMode appDataMode)
```

**Comment by IlyaBausovAkvelon** [comment] 2023-10-06 02:09
Hi @jeromelaban,
For now we don't support .NET 8. I've checked this problem and was able to reproduce it. If we will be implementing Xamarin.UITest support for .NET 8 we will fix it.

**Comment by IlyaBausovAkvelon** [comment] 2023-10-06 07:00
@jeromelaban How do you configure your app? Could you please show me line of code where you call ConfigureApp?

**Comment by evgenyvalavin** [comment] 2023-12-01 07:33
+1

**Comment by IlyaBausovAkvelon** [comment] 2023-12-19 02:03
@jeromelaban @evgenyvalavin Thank you for sharing this.

**Comment by zippo227** [comment] 2023-12-23 03:49
> Hi @jeromelaban, For now we don't support .NET 8. I've checked this problem and was able to reproduce it. If we will be implementing Xamarin.UITest support for .NET 8 we will fix it.

I hope that the team is able to support .net 8. With Xamarin Forms still considered to be in support and Visual Studio for Mac as well, until summer and fall 2024, Xamarin UI Test 8 support would encourage and help other developers like me who are transitioning to Maui.

**Comment by IlyaBausovAkvelon** [comment] 2023-12-26 09:28
@zippo227 for now we are not planning to add support for .NET 8.

**Comment by zippo227** [comment] 2024-01-14 23:58
> @zippo227 for now we are not planning to add support for .NET 8.

Hi Ilya, I saw your post and at the time it made sense. I worked on backporting my application .net 7. I was actually able to start a set of unit tests in .net 7, although I had to search for the simulator myself to be able to see it and it could only run on iphone 14. Unfortunately my ios tests did not complete. However, fortunately I have gotten my android tests to complete. I would just love to be able to run the same set of tests on ios in net 8. for some reason they cannot complete in .net 7 and moreover the maui app in .net 7 looks completely different. i don't know why it would be so different but it seems the fixes in .net 8 are so substantial that it is the only platform that supports my application. i would just love to be able to run the ui tests in .net 8 one last time to ensure parity. In search for an alternative i have glanced at what could be available in appium. however there is no support for creating an appium project. Please if you could point me in the right direction. I have the automation ids on my items. Thank you.

**Comment by dsmitchell** [comment] 2024-03-15 16:18
@IlyaBausovAkvelon, please either update for NET8 or open-source the code so that we can better work around issues.  Installing an app on a simulator and then launching it is as easy as:
```
Process.Start("xcrun", $"simctl boot {udid}").WaitForExit();
Process.Start("xcrun", $"simctl install {udid} {appPath}").WaitForExit();
Process.Start("xcrun", $"simctl launch {udid} {bundle}").WaitForExit();
```
And I wish the `.ConnectToApp()` method worked, but for some reason after successfully establishing a connection with Calabash on port 37265 the Xamarin.UITest code switches to port 27753 and fails, even with the code below:
```
var config = ConfigureApp.iOS
    .AppBundle(appPath) // This doesn't help or hurt, but I'm leaving it here for reference
    .Debug()
    .DeviceIdentifier(udid)
    .DeviceIp("127.0.0.1")
    .DevicePort(37265)
    .EnableLocalScreenshots();

iOSApp app = config.ConnectToApp(); // Succeeds on port 37265
Thread.Sleep(2000);
app.Flash(); // Fails on port 27753
```

**Comment by JohnHDev** [comment] 2024-05-25 21:19
@IlyaBausovAkvelon has Xamarin.UITest been deprecated? I haven't seen an announcement for that, and if not, then why won't .NET 8 be supported? We are using Xamarin.UITest to automate tests on out .NET Maui app, that's on .NET 8 but our test projects need to be .NET 7?

Long term, will Xamarin.UITest be open sourced? Would be very useful if so.

Thanks
John

**Comment by jeromelaban** [comment] 2024-06-06 03:05
For those of you hitting this issue, the breaking change came with .NET 8, where [`Environment.GetFolderPath(Environment.SpecialFolder.Personal)`](https://github.com/dotnet/runtime/blob/60edbf9371ff00349e9224fb0920c8bca51f1a4f/src/libraries/System.Private.CoreLib/src/System/Environment.GetFolderPathCore.Unix.cs#L105) used to return `~`, and now returns `~/Documents`. 

The effect of this change is that Xamarin.UITest cannot find the `device.plist` info from the selected simulator.

A possible workaround is as follows, until Xamarin.UITest is fixed:

```bash
ln -s ~/Library ~/Documents/Library
```

This will make the simulator files visible to Xamarin.UITest.

For the Microsoft team (@IlyaBausovAkvelon), the fix is to use `Environment.SpecialFolder.UserProfile` instead of `Environment.SpecialFolder.Personal`.

**Comment by dsmitchell** [comment] 2024-06-06 03:10
> For those of you hitting this issue, the breaking change came with .NET 8, where [`Environment.GetFolderPath(Environment.SpecialFolder.Personal)`](https://github.com/dotnet/runtime/blob/60edbf9371ff00349e9224fb0920c8bca51f1a4f/src/libraries/System.Private.CoreLib/src/System/Environment.GetFolderPathCore.Unix.cs#L105) used to return `~`, and now returns `~/Documents`.
> 
> The effect of this change is that Xamarin.UITest cannot find the `device.plist` info from the selected simulator.
> 
> A possible workaround is as follows, until Xamarin.UITest is fixed:
> 
> ```shell
> ln -s ~/Library ~/Documents/Library
> ```
> 
> This will make the simulator files visible to Xamarin.UITest.
> 
> For the Microsoft team (@IlyaBausovAkvelon), the fix is to use `Environment.SpecialFolder.UserProfile` instead of `Environment.SpecialFolder.Personal`.

Nice find. I will try this tomorrow in our own pipelines.

It's almost as if AppCenter should pay you to do their work...

**Comment by IlyaBausovAkvelon** [comment] 2024-06-07 09:15
Hi all,
We've released Xamarin.UITest 4.3.5 which has a fix for this issue with the simulators so no need to use symlink to the folder mentioned above. For now this version should be working fine with .NET 8 target framework. Thank you all for the patience.

**Comment by jeromelaban** [comment] 2024-06-07 14:36
@IlyaBausovAkvelon This is working for us! Thanks for the new release.

**Comment by JohnHDev** [comment] 2024-06-08 17:18
@IlyaBausovAkvelon I have updated and now getting the following error:
	Message	"One or more errors occurred. (Failed to launch simulator: An error occurred trying to start process 'idb:' with working directory '/Users/jxxxxx/bin/Debug/net8.0'. No such file or directory)"

The path definitely exists however. Any pointers on what might be wrong?

**Comment by IlyaBausovAkvelon** [comment] 2024-06-26 01:48
@JohnHDev probably it's happening because of idb paths. Could you please try to use OverrideIDBPath when configure iOSApp? The OverrideIDBPath was added to 4.3.7 release.

**Comment by DmitriyKirakosyan** [comment] 2024-06-27 09:57
The initial issue was fixed, so I'm closing it.

**Closed by DmitriyKirakosyan** 2024-06-27 09:57 UTC
Labels: feature request, test
