### ISSUE TITLE
Can we make the target a dynamic framework?

### ISSUE THREAD

**Issue by huahuahu** [microsoft/appcenter#2596] opened 2023-10-26 09:35 UTC
**Describe the solution you'd like**
Make the final output as a dynamic framework so it can be shared between different targets, specially between main app and Share Extension. This can make the final ipa size smaller.

**Describe alternatives you've considered**
Each target has its own copy of the static framework.

Below is the result. The sybmol is linked in multiple targets.
![image](https://github.com/microsoft/appcenter/assets/5757671/4aa42b4a-0123-478a-942e-e4f643dac083)

**Comment by DmitriyKirakosyan** [comment] 2023-10-31 08:03
Duplicate of https://github.com/microsoft/appcenter-sdk-apple/issues/1227.

@huahuahu , unfortunately, we do not have plans to add support for this feature in the next year.

**Closed by DmitriyKirakosyan** 2023-10-31 08:03 UTC
Labels: feature request, sdk
