### ISSUE TITLE
Support for .Net 5.0

### ISSUE THREAD

**Issue by sawankumarbundelkhandi** [microsoft/appcenter#2064] opened 2020-12-03 17:11 UTC
**Describe the solution you'd like**
 I am using AppCenter for Xamairn and I have updated my code to support C# 9. It's not compiling on AppCenter anymore.

Is there any roadmap to support .Net 5.0?

**Describe alternatives you've considered**
For now, I have created a post clone script following this - https://codetraveler.io/2019/08/23/using-preview-versions-of-net-core-with-app-center-build/

**Comment by wham** [comment] 2020-12-04 05:56
Duplicate of https://github.com/microsoft/appcenter/issues/86. We are working on .NET 5.0 support. Should be available by the end of the year.

**Closed by wham** 2020-12-04 05:56 UTC
Labels: feature request

**Comment by SuperCorks** [comment] 2021-03-31 13:05
@sawankumarbundelkhandi did you manage to get it to work with a post-clone script? Can you provide an example? Thanks in advance.
