### ISSUE TITLE
WinForms SQLite errors on Startup

### ISSUE THREAD

**Issue by bvanderw** [microsoft/appcenter#2527] opened 2023-03-10 20:43 UTC
Windows 11
Visual Studio 2022
AppCenter 5.0.1

To isolate another issue I am having, I created a new WinForms app with ,NET Framework 4.8 and added the Crashes and Analytics NuGet packages.

On startup, I am getting the following error:

2023-03-10 15:26:08.523 [AppCenter] ERROR: Failed to initialize sqlite3 provider.
System.Exception: Library e_sqlite3 not found

I noticed that the runtimes folder and content are not being created in the bin folder.

I have attached the full debug log.
[SqliteIssue.log](https://github.com/microsoft/appcenter/files/10945928/SqliteIssue.log)

**Comment by MikhailSuendukov** [comment] 2023-03-13 11:19
Hi @bvanderw. It seems that this is a duplicate of [this](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1716) issue. And now we have [workaround](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1716#issuecomment-1438139941) for that. I close this issue as a duplicate, but if you still have any questions, you can freely reopen this issue or use an already created one.

**Closed by MikhailSuendukov** 2023-03-13 11:19 UTC
Labels: duplicate
