### ISSUE TITLE
Xamarin.iOS after adding App Center SDK project could not build - MT5212

### ISSUE THREAD

**Issue by ideveloperaz** [microsoft/appcenter#843] opened 2019-08-08 11:50 UTC
**What App Center service does this affect?**
Crashes

**Describe the bug**
Xamarin.iOS after adding App Center SDK project could not build getting following error:
MT5212: Native linking failed, duplicate symbol: *.
this error points to duplicate symbols in MobileVLC and PortSIP libs

if I remove App Center SDK I could build project without problems

**To Reproduce**
1. existing project with MobileVLCKit and PortSIP SDK implemented
2. I moved from hockeyapp to App Center SDK like it is said in documentation 
3. Just did a minimal required setup to use App Center SDK and project could not build 

only adding "-gcc_flags -dead_strip" to compiler fixed that issue .

**Expected behavior**

**Screenshots**
![Screen Shot 2019-08-08 at 2 29 13 PM](https://user-images.githubusercontent.com/2921595/62699388-78b61800-b9f0-11e9-9518-2d3831a5ece1.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hamswan** [comment] 2019-08-09 00:03
We are looking into this.

**Comment by MatkovIvan** [comment] 2019-08-09 09:39
Hi @ideveloperaz,

The duplicate symbol in this build is not related to AppCenter SDK, but it is a valid error message in your case.  Based on the errors from your screenshot - both MobileVLCKit and PortSIP SDK contain "Secure RTP" implementation.
So, the dependencies of your project contain duplicated symbols - it's the root cause of it.

Since you have already solved this issue, you (most likely) have already seen the doc with detailed information of this error: [MT5212: Native linking failed, duplicate symbol: *](https://docs.microsoft.com/en-us/xamarin/ios/troubleshooting/mtouch-errors#mt5212-native-linking-failed-duplicate-symbol-)

Similar issue: https://github.com/microsoft/appcenter-sdk-dotnet/issues/816

Closing this as it's not related to AppCenter.

**Closed by MatkovIvan** 2019-08-09 09:39 UTC
Labels: sdk, support

**Comment by ideveloperaz** [comment] 2019-08-09 09:53
Hi @MatkovIvan thank you for reply, but what is interesting if I remove AppCenter I could compile project without problem with the same MobileVLC and PortSIP integrated .... anyway
