### ISSUE TITLE
FOOM (fatal out of memory error) not being recorded

### ISSUE THREAD

**Issue by fosterbrereton** [microsoft/appcenter#650] opened 2019-06-28 23:33 UTC
**What App Center service does this affect?**
HockeyApp - iOS

**Describe the bug**

Given unusual memory allocation conditions, it is possible for our application to terminate unexpectedly. The problem is that on subsequent re-launch of the app, there is no indication that a crash has happened. We suspect this is due to an `EXC_RESOURCE` mach exception is being thrown to the application, but is not being handled/reported the same way as other mach exceptions are.

**To Reproduce**

On a 12.9" iPad Pro the following code can cause the application to terminate due to an out of memory error. Upon relaunch, the HockeyApp SDK does not appear to record a crash:

```objectivec++
+(void) fatalMemoryAllocation {
    constexpr auto size_k{1024UL * 1024 * 1024}; // 1GiB
    while (true) {
        volatile auto foo = new char[size_k];
        std::fill(foo, foo + size_k, 42);
        NSLog(@"Allocated %ld bytes", size_k);
    }
}
```

**Expected behavior**

It would be great if this class of app termination were caught and handled similar to the others.

**Screenshots**

Though not a screenshot, when the application is run while _not_ attached to a debugger, I see the following in the device logs shortly after the application is preempted:

```default 20:59:13.099559 -0700   MyApp Allocated 1073741824 bytes
default 20:59:13.552536 -0700   kernel  EXC_RESOURCE -> MyApp[29847] exceeded mem limit: ActiveHard 3072 MB (fatal)
default 20:59:13.552690 -0700   kernel  464154.287 memorystatus: killing_specific_process pid 29847 [MyApp] (per-process-limit 10) - memorystatus_available_pages: 50959
```

**Smartphone (please complete the following information):**
 - Device: iPad Pro 12.9" (and others)
 - OS: iOS 12.x

**Additional context**

I have already posted about this issue on the [HockeySDK-iOS project](https://github.com/bitstadium/HockeySDK-iOS/issues/554).

**Comment by lumaxis** [comment] 2019-07-01 11:35
Referencing [my comment](https://github.com/bitstadium/HockeySDK-iOS/issues/554#issuecomment-507227019) from https://github.com/bitstadium/HockeySDK-iOS/issues/554 here too:
>@fosterbrereton While I think the App Center SDK does not yet have this feature, you could try using https://www.hockeyapp.net/help/sdk/ios/5.1.4/Classes/BITCrashManager.html#/c:objc(cs)BITCrashManager(py)enableAppNotTerminatingCleanlyDetection now that you are still using the HockeySDK.
It's not 100% accurate and can include reports from other reasons but it should theoretically provide you with info about how often your app gets killed for using too much memory.

@elamalani I remember we talked about porting this/a similar feature over to the App Center SDK, do you know what the current status of that is?

**Comment by lumaxis** [comment] 2019-07-01 18:05
Actually, I think this is a duplicate of #103 🙂

**Comment by hamswan** [comment] 2019-07-17 23:13
@fosterbrereton our Dev team will look into this.

**Comment by DmitriyKirakosyan** [comment] 2024-06-27 07:00
As we do not have plans to add support for this feature in the next year, I'm closing the issue.

**Closed by DmitriyKirakosyan** 2024-06-27 07:00 UTC
Labels: bug, hockeyapp, sdk
