### ISSUE TITLE
Unable to build react native apps with XCode 10 build system

### ISSUE THREAD

**Issue by barryelevatyr** [microsoft/appcenter#364] opened 2019-04-30 21:01 UTC
**What App Center service does this affect?**
build

**Describe the bug**
AppCenter build currently forces the use of the XCode legacy build system by passing `UseModernBuildSystem = NO` on the command line to XCode.  Due to this forced behavior, customers are unable to build using the XCode 10 build system.

**To Reproduce**
1. Configure an RN Build setting XCode to 10.x ensuring that no value is set for `BuildSystemType` in workspace file
2. Run build

**Expected behavior**
Build uses new build system

**Actual behavior**
Build uses legacy build system because `UseModernBuildSystem = NO` is passed on command line.  Build output includes:
```
User defaults from command line:
    UseModernBuildSystem = NO
```

**Additional context**
While it is still known to have some lingering issues, RN has supported XCode 10 build system since 0.58.  For those having issues, RN clearly documents that controlling the build system via the workspace setting is the proper way to ensure the legacy build system is used.  Controlling the build system used is an XCode "feature", not an RN specific "feature."

I understand that AppCenter team was trying to help customers avoid issues but this should/could have been implemented a better way.  For example, a checkbox/dropdown on the build configuration tab called "Build System" with a default of "Legacy".  This still accomplishes your goal of "helping" customers but gives them the ability to control their build when they know it will work with the new build system.  The checkbox/drop-down can have an info icon providing customers information about the build system types, links to information about known issues with new build system, etc.  In short, give your customers the information and let them make an informed decision.

The workspace setting is there for a reason - it puts the control in the developers hand rather than having AppCenter unilaterally make a decision to force a configuration on its customers.  As it stands, customers are unable to build RN apps using 10.x build system and therefore this should be considered a bug and addressed.

**Comment by mcarlson** [comment] 2019-05-01 00:41
Please, please fix this. Our app uses a library that requires XCode 10 (RNIap) and between this issue and https://github.com/Microsoft/appcenter/issues/112 we can't use Appcenter for iOS builds at all anymore...

**Comment by DennisPan** [comment] 2019-05-01 04:58
Thanks for bringing this up! We are looking at this now, and will circle back soon.

**Comment by barryelevatyr** [comment] 2019-05-01 07:49
@DennisPan - Thank you for your quick attention to this, greatly appreciated!

**Comment by DennisPan** [comment] 2019-05-02 08:26
@barryelevatyr @mcarlson The current thinking is that we will switch to use new build system by default if RN version is 0.59 or later. In the meantime, provide a way to override that to use legacy. Most likely through the branch configuration (need a bit more detailed technical investigation)

This applies to any new branch configurations. Existing ones will remain on legacy as default, and can change to use new build system by re-saving it.

We haven’t formalized all required details yet, or have the work officially prioritized. Thought worth sharing an update on where we are heading.

cc @nrajpurkar

**Comment by barryelevatyr** [comment] 2019-05-02 08:52
@DennisPan Appreciate the quick triage on this and the update.  A few thoughts/comments:

1. For RN < 0.59, based on your description, it would default to legacy.  It's not clear if there would be a choice to override to new build system in this case or if only RN >= 0.59 would have the choice (with their default new build system).  I would strongly encourage all users regardless of RN version have the choice even if the default is different (although I don't think there's a need to differentiate the default - see further bullets).  I've been using new build system on dev machines since 0.58 without any issues.  
2. To simplify, my thoughts are to always expose the branch configuration whenever XCode >= 10 is chosen in build configuration regardless of RN version and don't expose it (as it wouldn't apply anyway) if XCode < 10.  This would likely negate the need for your team to worry about how to detect/manage RN version used which should shorten the cycle to release the fix.
3. For consistency, always have the default build system legacy for existing build configurations - new build configurations could default to new build system.  This simplifies having to determine which default to apply based on which RN version.  Also eliminates having to handle the situations where a commit upgrades the RN version, etc. 
4. Agreed 100% that existing branches should remain as is even with the new setting.  Re-save would be required to "apply" the new options/config.  This avoids any regressions for existing customers.

Look forward to future updates and a timeline as they are available.  Thank you!

**Comment by DennisPan** [comment] 2019-05-03 05:47
Thanks for the detailed suggestion @barryelevatyr ! Couple comments:

1. Yes. Any RN version will have the option, as long as Xcode 10 and above is selected. I believe this should address what @mcarlson raised in #112 
2. We like the suggestion of keep default consistent 👍 . We will use new build system as default for any **new** configuration (applies to all RN versions). Existing branch configurations will remain on legacy, until customers edit and re-save.
3. As for "Use Workspace Setting", great idea ❤️. However we won't be able to address now. I'd encourage create a new Issue, if that's something you are interested in.

In terms of timeline, we consider this high priority, and will start soon. The change isn't huge. But given other priorities in progress, my hope is to deliver this in two weeks the latest.

**Comment by barryelevatyr** [comment] 2019-05-03 06:27
@DennisPan - Appreciate the update and the team's welcoming of the feedback, glad to see it incorporated!

Couple of questions/thoughts:
1) Great news about all RN versions having the option if XCode >= 10 and default being consistent!
2) Given your #3, if I'm understanding correctly, this means that you will still pass `-UseModernBuildSystem` flag - it will just be conditionally YES or NO depending on the build config.  Assuming this is the case, I'd suggest that the only time `-UseModernBuildSetting` is supplied on command line is when user has chosen "Legacy Build System."  In the case of using the new build system, there isn't a need to specify `-UseModernBuildSystem` at all.  Rather, XCode will use the new build system (assuming XCode >= 10) unless there is a workspace setting (`BuildSystemType`) configured to use legacy build system (Xcode Files-> Project/Workspace Settings as described [here](https://medium.com/xcblog/five-things-you-must-know-about-xcode-10-new-build-system-41676cd5fd6c)).  Going this route provides flexibility for users who want to force the old build system used or want to control themselves via workspace (XCode recommended way of doing this) as well as future proofing to avoid passing `-UseModernBuildSystem` when XCode decides to change the options/usage.

The one question I would have given my #2 is whether or not a "force" option in AppCenter build config would be required to solve @mcarlson issue.  If his scenario requires being able to force AppCenter to always pass -UseModernBuildSystem, then having a drop down with "Force Legacy" (AppCenter passes -UseModernBuildSystem=NO), "Force Modern" (AppCenter passes -UseModernBuildSystem=YES) and "Use Default" (AppCenter passes nothing) would seem fairly straightforward to implement with all new branches receiving "Use Default" as the default.

@mcarlson - Thoughts on what's required for your scenario?

**Comment by DennisPan** [comment] 2019-05-03 22:08
@barryelevatyr Thanks for pointing out the case of using workspace setting. I'm starting to think if we are over thinking this. If using what's set in workspace setting is a viable option, do we still need to provide the ability to force legacy or new build system?

Basically here's another option:
1. For **RN >= 0.59** or **unknown version** (e.g. custom RN source used, like @mcarlson does), always **use workspace setting**. If workspace setting is not committed to repo, it defaults to new build system. For RN, `project.xcworkspace` is by default in `.gitignore` (https://github.com/facebook/react-native/blob/master/template/_gitignore#L23)
2. For **other versions**, always **force legacy** build system. The reason we added that in the first place was because many customers run into failure after switching to Xcode 10. Looking at our telemetry, there is still a good number of customers on RN < 0.58 (_note: not 0.59 here_)

Let us know what you think. Happy to hear if there is a valid use case to not rely on workspace setting (for RN >= 0.59).

**Comment by barryelevatyr** [comment] 2019-05-04 00:51
@DennisPan - Thanks for the continued exploration on this and yes, I do think we are overthinking :)

However, I think we're overthinking because of the current state that we have to account for.  In short, IMHO, there was never a need to force `-UseModerBuildSystem=NO`.  In fact, with all due respect, I think it was an improper decision.  Let me explain...

When customers started having issues with RN builds on XCode 10, the RN community/docs/etc. all acknowledged the limitations/issues and provided guidance on how to set the workspace setting.  Given this, AppCenter really didn't need to do anything except instruct customers to configure the workspace setting.  This could have been done via a number of different communication channels.  To summarize, the correct way for customers to control their build system is via the workspace and having AppCenter unilaterally force legacy on customers was a poor decision.  Understand that it was intended to help customers, but as RN matured and XCode 10 support was improved (it's been working since October of last year), now AppCenter customers have no way to use the new system.  Had the forced command line never been added and customers just instructed to use the workspace, all would have been good :) Hindsight always 20/20 and again, understand you guys were trying to help but there's some lessons to be learned here :)

Fast forward to today - customers using AppCenter may or may not be relying on the fact that legacy build system is forced.  I'd venture to guess that a large majority of customers don't even know that they are using the legacy build system when building on appcenter and likely don't even know that there are two build systems.  I think this is why the issue hasn't been raised previously.

So, given there's a baseline with the forced and its something we have to account for, I think your latest line of thinking is the way I would go if it were my decision with a few minor tweaks:

1) All existing build configurations remain on forced legacy regardless of RN version
2) Add a checkbox on build configuration called "Force Legacy Build System" with a default to "checked" for existing build configuration and "not checked" for new build configurations.  This is required because you need to be able to continue to allow existing customers with existing build configurations to make other changes to their build configs (which requires saving) while continuing to "force legacy" (even though they really should be using workspace setting) since removing this would be considered a regression in their eyes.
3)  I don't see any need to differentiate on RN version.  The above 2 items should address all known situations and give customers full control over their scenario.
4) Communicate the information to customers (whichever channel(s) you feel most appropriate) explaining the options, pointers to XCode docs explaining the setting, pointers to RN docs/github issues, etc.
5) Inform your support team and others internally about how to handle customer support issues that are going to still come in.  These cases should be relatively easy to handle with a quick explanation on why customers builds are failing and the quick step to resolve (set the workspace) or check the checkbox.

I think there is a case to be made for NEW build configurations to check RN version and if < 0.58 _(note: not equal to 58)_ were support for new system was greatly improved, defaulting the "force legacy build system" checkbox to true but I really do not think it's necessary as the workspace setting is the official RN & XCode way to address this.

Hope this helps.  Look forward to your thoughts.

**Comment by DennisPan** [comment] 2019-05-06 05:50
Thanks again for the detailed write up @barryelevatyr 

The solution you described above makes sense to me. What I'm not sure about is whether we want to use new build system by default for RN < 0.58. We are where we are because of a good load of RN customer escalations when Xcode 10 initially rolled out. Will discuss with team.

As for your additional input # 2, you are right that `project.xcworkspace` is not the file. But by default, `WorkspaceSettings.xcsettings` is under `project.xcworkspace`, which means by default it's not committed in the repository. I checked a new project (from `react-native init`), it's under `ios/<projectname>.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings`

**Comment by barryelevatyr** [comment] 2019-05-06 07:57
Completely understand that the forced legacy build was introduced to handle the customer issues/fallout when XCode 10 shipped.  Just wish there was a toggle from the outset (short of customers just relying on workspace) rather than forced across the board :)

I can see reasons to default legacy for < 0.58 and reasons not to.  One thing to consider along this line is that if customers are < 0.58 and they are using XCode 10, their builds are likely failing on dev machines so they would have to use the workspace setting there anyway.  Possibly there are other workarounds/solutions that I'm not aware of.  That said, it's also very possible that customers are still using XCode 9 on dev but have chosen 10.x on appcenter (not a best practice but have to imagine it's happening).  I think if you do decide to conditionally default based on RN version, that old & new configs should both have the checkbox option (assuming you are thinking similarly).  The downside to that, of course is that it's something that has to be supported/maintained for the foreseeable future as Xcode & RN both evolve.

Regarding the `WorkspaceSettings.xcsettings`, thanks for pointing that out!  I am encountering a different experience than what you did so possibly we have taken slightly different steps.  My `WorkspaceSettings.xsettings` ends up under` ios/<projectname>.xcworkspace/xcshareddata` (e.g. `ios/RN0595Test.xcworkspace/xcshareddata`) so it's not excluded by the default `gitignore`.

**Comment by DennisPan** [comment] 2019-05-07 16:37
@barryelevatyr Here's what we decided to implement:

1. Add a toggle "Force Legacy Build System" to branch configuration for RN iOS apps.
2. The toggle is enabled only for Xcode 10 and above. But is always visible.
3. The toggle is on by default for these cases:
   - RN < 0.58
   - Existing branch configurations
4. All other cases have the toggle off by default. This means using apps' workspace setting to determine build system

Thanks again for your great feedbacks! Appreciate the level of details and insightful thoughts. Implementation has just started.

**Comment by barryelevatyr** [comment] 2019-05-07 17:58
@DennisPan - Sounds like a good plan, looking forward to the release of this.  Thanks you and the team's quick attention to this, greatly appreciated!

**Comment by mcarlson** [comment] 2019-05-08 02:20
@DennisPan @barryelevatyr Do you know when it will be available for us to use? We are currently upgrading to RN 0.59 so this is going to be critical for us very soon. Thanks so much for working towards resolving this!

**Comment by DennisPan** [comment] 2019-05-08 04:02
@mcarlson Currently targeting end of next week

**Comment by DennisPan** [comment] 2019-05-16 19:37
@barryelevatyr @mcarlson We just released the changes. Do you want to give it a try?

**Comment by barryelevatyr** [comment] 2019-05-17 01:56
@DennisPan - Great news, thank you and the team again for turning this around quickly!

First, some smoke testing and good news:
1) Opened existing build on 10.2, "force legacy" toggle was "on" - PASSED
2) Create new build for new branch on 10.2, "force legacy" toggle was "off" - PASSED
3) Change XCode to 9.4 on both above branches, "force legacy" toggle was "disabled" - PASSED
4) Build existing build on 10.2 without changing "force legacy", build forced old build system & built successfully - PASSED

Now, unfortunately, for the bad news:
1) Changed existing build config "force legacy" toggle to "off"
2) Ran Build
3) Build Failed

The build completes successfully locally using XCode and react-native run-ios both using the new build system.  The error message in AppCenter is

```
error: Multiple commands produce '/Users/vsts/Library/Developer/Xcode/DerivedData/Elevatyr-frwhutravdjjqfcymjeiapjqfzre/Build/Intermediates.noindex/ArchiveIntermediates/Elevatyr/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libyoga.a':
1) Target 'yoga' has a command with output '/Users/vsts/Library/Developer/Xcode/DerivedData/Elevatyr-frwhutravdjjqfcymjeiapjqfzre/Build/Intermediates.noindex/ArchiveIntermediates/Elevatyr/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libyoga.a'
2) Target 'yoga-tvOS' has a command with output '/Users/vsts/Library/Developer/Xcode/DerivedData/Elevatyr-frwhutravdjjqfcymjeiapjqfzre/Build/Intermediates.noindex/ArchiveIntermediates/Elevatyr/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libyoga.a'

```

I did some digging on this and it appears that the key difference between the xcodebuild command that AppCenter uses and the ones that XCode & RN run-ios use is that AppCenter includes the "-sdk iphoneos" option whereas the other two include destination option.

I know very little about iOS native dev nor XCode but from what I can tell, passing SDK will produce all artifacts defined (iOS, tvOS) while passing destination will just build that artifact.  This is why we see the duplicate error in AppCenter but not in the other tools.

I reproduced a similar issue creating a brand new RN app (react-native init) and executing the AppCenter xcodebuild command.  My project uses Cocoapods but this confirms that the issue exists in either scenario (my project does contain the "remove target" logic in my podfile for yoga & react).  The command I executed to mirror AppCenter is:

`xcodebuild -project ./ios/RN0595Test.xcodeproj -scheme RN0595Test archive -sdk iphoneos -archivePath ./build/archive/RN0595Test CODE_SIGN_STYLE=Manual`

There is an [RN issue](https://github.com/facebook/react-native/issues/20492) regarding this error but it is marked closed.  I'm guessing it is marked closed because all of the "RN" tools build successfully because they do not pass the "sdk" option.  Although, as [this comment](https://github.com/facebook/react-native/issues/20492#issuecomment-464733388) points out, possibly RN has some more work to do or if this is a bug in XCode.

For completeness, the command react-native run-ios uses is:
`xcodebuild -project RNTest0595Test.xcodeproj -configuration Debug -scheme RNTest0595Test -destination id=A75B443F-81AC-4800-AC5B-5E2CF9A031F3 -derivedDataPath build/RNTest0595Test`

Unfortunately, I'm unable to figure out how to actually determine what exact command line XCode uses to build or archive projects.  I checked the build log but it doesn't provide the command itself - if anyone knows how to obtain this information any insight is appreciated.

If there's any other information I can provide you regarding troubleshooting this, please let me know.  In the meantime, I'm going to continue to investigate options.

Thanks!

**Comment by DennisPan** [comment] 2019-05-17 07:25
@barryelevatyr Thanks for giving it a try and the detailed investigation! We are looking into this. For the time being, we are considering making "force legacy" toggled to "on" by default for any RN version, so that we provide a better onboarding experience. It's always sad to see your first build fail, and not everyone have the resource and energy to figure out changing the build system as a workaround. Once we have a better solution with the new build system, then we can change the default.

**Comment by barryelevatyr** [comment] 2019-05-17 18:23
@DennisPan I think changing the default to "on" is the right call given what we know at this point.  I think there are some scenarios that will build successfully with the new build system even with the "sdk" option passed so offering the flexibility makes sense even at this point.  

As an example, I tried to strip all React libraries/frameworks from my main project (one of the suggestions in the RN github issue) and only having them in Pods project and this seemed to work except for the fact that AppCenter SDK places code in both the Main project and the Pods project so the Main Project fails to build due to removal of React from Main Project (not clear why the AppCenter SDK puts code in both Main & Pods project - any insight would be appreciated).  The workaround for this is to likely add SourcePath to main project for React files but that all seems a little too hacky at this point.

I think the key question is whether or not the "sdk" option should be passed and/or if another should be passed with it since neither RN or even XCode itself pass this option (or possibly XCode does but also includes another option).

Look forward to updates from your side and will continue to research on my end as well.  Thanks!

**Comment by barryelevatyr** [comment] 2019-05-17 20:27
@DennisPan - Some additional information from the above...

I installed a tool called [Fastlane](https://github.com/fastlane/fastlane) which is an automation tool used throughout the community to see what their default command line is for building apps.  Using the stock defaults for Fastlane after setting up the fastfile, the command used was:

`xcodebuild -workspace RN0595Test.xcworkspace -scheme RN0595Test -destination 'generic/platform=iOS' -archivePath /Users/barry/Library/Developer/Xcode/Archives/2019-05-17/RN0595Test\ 2019-05-17\ 13.11.45.xcarchive archive`

Notable here is the lack of "sdk" option and the presence of "destination" option.  Unfortunately, I'm not familiar enough with XCode to say which one is the "recommended" way to execute xcodebuild but given RN, XCode and now FastLane all use "destination" vs. "sdk", possibly the solution here is changing the command line AppCenter uses to build RN projects?

**Comment by DennisPan** [comment] 2019-06-19 16:53
@barryelevatyr @mcarlson  Sorry this unexpected took a long time. We are ready to give this a try now. Basically we are removing `-sdk` option when modern build system is used. If you can email me (find my email in my profile) your App Center user name and the app, I can enable the feature flag for it to try.

**Comment by DennisPan** [comment] 2019-06-24 05:42
This change is now globally enabled for everyone 🎉 . If your RN build does not force legacy build, then re-save the configuration will remove the `-sdk` option in `xcodbuild` command. We didn't add `-destination` option because it defaults to a device compatible with selected scheme. 

Special thanks to @barryelevatyr for the great partnership along the process! Thanks everyone for taking the time to reach out.

Closing this now. Let us know if things are not working. Feel free to re-open the Issue.

**Closed by DennisPan** 2019-06-24 05:42 UTC
Labels: bug, build

**Comment by yairk** [comment] 2019-06-30 08:08
Just to give another perspective - our iOS RN builds on AppCenter recently started producing IPAs that would not load on iPhones. This happened without any code change from our side. After a good few hours of poring over build logs, it seemed that the cause was the removal of the `-sdk` option in the `xcodebuild` command line.

It seems that someone changed something unrelated in our project AppCenter configuration which caused this change to apply.

It is entirely possible that this indicates something deep in our project files is wrong, and I would be happy to find out how to fix it. But I must say it's an unpleasant experience to have seemingly corrupt build outputs without any change from our side, simply because AppCenter's defaults have changed in a way that's undocumented even in the [Change Log](https://docs.microsoft.com/en-us/appcenter/general/changelog). Luckily we found this issue here, and enabling the Legacy Build system for our project resolved the problem (BTW, we were using the Legacy Build in our workspace settings, but AppCenter was unaware of this).

Not sure what the best way forward is, in terms of rolling out new features, but I think that since builds are often quite fragile, caution should be exercised when changing the way existing builds are performed. @DennisPan How do you see this?

**Comment by DennisPan** [comment] 2019-07-01 22:01
@yairk Thanks for the input! I agree that we could have considered more cases, or at least better communications on this. The change was supposed to be for anyone adopting modern build system only. What you saw (using legacy build in workspace setting but App Center ignored it) sounds like a bug. We are investigating. May reach out to you later if we need more information from you.
