### ISSUE TITLE
Add support for writing Appium tests with node.js

### ISSUE THREAD

**Issue by sbcodes** [microsoft/appcenter#1973] opened 2020-08-26 09:28 UTC
**Describe the solution you'd like**
Writing Appium tests with Java and JUnit has limited support for Flutter applications which makes writing the test in this format very challenging. The main issue being there are not many ways to search for elements effectively. However there is a node package called appium-flutter-driver that allows for effective searching along with other useful features specifically for flutter. Using this package would require support for running tests with NodeJS but would allow for reusing tests for both Android and iOS.

**Describe alternatives you've considered**
I've found a Java library for using valueKeys to find flutter elements however this only seems to have support for running tests on iOS and doesn't seem to be in active development anymore.

**Comment by sbcodes** [comment] 2020-08-26 13:34
#453 Would solve this issue too

**Comment by mapo80** [comment] 2020-12-09 17:01
News?

**Comment by nikita-potashev** [comment] 2021-01-29 14:55
Duplicate of #453

**Closed by nikita-potashev** 2021-01-29 14:55 UTC
Labels: feature request, test
