### ISSUE TITLE
Honour CI Ignore tag

### ISSUE THREAD

**Issue by anthonyhumphreys** [microsoft/appcenter#930] opened 2019-08-21 19:59 UTC
**Describe the solution you'd like**
I would like to be able to add a flag which will prevent build on push.

Sometimes a hotfix is rolled out which hits the branch listened to by AppCenter and this only needs a codepush deploy, not a native build. In this case it would be great to be able to add a NO_CI type flag to a commit.

I would love for this to be configurable in the branch config, so that you could distinguish between platforms. E.g. where I build for iOS and Android sometimes a release only needs to hit Android CI.

**Describe alternatives you've considered**
Not sure but anything that gave this kind of functionality

**Additional context**
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#skipping-ci-for-individual-commits

**Comment by nrajpurkar** [comment] 2019-08-21 20:05
Hi @anthonyhumphreys, thanks for this feature request! Looks like a possible duplicate of #54. Closing this out and feel free to leave some additional comments there.

**Closed by nrajpurkar** 2019-08-21 20:05 UTC
Labels: build, feature request

**Comment by anthonyhumphreys** [comment] 2019-08-21 20:07
Ah i was about to close this myself actually, thought it was a duplicate of #26
